/* Non-code words in __text (switch offset tables, alignment padding), read from the binary. Generated by Tools/userspace/raw_emit.py */
/* 0x20f4-0x2100 padding */
const unsigned int text_data_20f4[3] = {0x00000000, 0x00000000, 0x00000000};
/* 0x2308-0x2310 padding */
const unsigned int text_data_2308[2] = {0x60000000, 0x60000000};
/* 0x2334-0x2340 padding */
const unsigned int text_data_2334[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x23ac-0x23b0 padding */
const unsigned int text_data_23ac[1] = {0x60000000};
/* 0x24f4-0x2500 padding */
const unsigned int text_data_24f4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x256c-0x2570 padding */
const unsigned int text_data_256c[1] = {0x00000000};
/* 0x2904-0x2910 padding */
const unsigned int text_data_2904[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2924-0x2930 padding */
const unsigned int text_data_2924[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x29b4-0x29c0 padding */
const unsigned int text_data_29b4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2b68-0x2b70 padding */
const unsigned int text_data_2b68[2] = {0x60000000, 0x60000000};
/* 0x2c64-0x2c70 padding */
const unsigned int text_data_2c64[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2cf4-0x2d00 padding */
const unsigned int text_data_2cf4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2d78-0x2d80 padding */
const unsigned int text_data_2d78[2] = {0x60000000, 0x60000000};
/* 0x2e04-0x2e10 padding */
const unsigned int text_data_2e04[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2e98-0x2f00 table switch table of the `bctr` at 0x2e94: entry i -> 0x2e98 + word[i]; targets 3094 2f00 2f00 2f00 2f00 2f00 2f00 2f00 2f00 2f00 2f00 2f00 2f00 2f00 2f00 2f00... */
const unsigned int text_data_2e98[26] = {0x000001fc, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x00000068, 0x000000d0, 0x00000124, 0x0000016c, 0x000001b4, 0x00000220, 0x0000007c, 0x60000000};
/* 0x318c-0x3190 padding */
const unsigned int text_data_318c[1] = {0x60000000};
/* 0x31bc-0x31c0 padding */
const unsigned int text_data_31bc[1] = {0x60000000};
/* 0x320c-0x3210 padding */
const unsigned int text_data_320c[1] = {0x60000000};
/* 0x3234-0x3240 padding */
const unsigned int text_data_3234[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x3348-0x3350 padding */
const unsigned int text_data_3348[2] = {0x60000000, 0x60000000};
/* 0x355c-0x3560 padding */
const unsigned int text_data_355c[1] = {0x60000000};
/* 0x35e4-0x35f0 padding */
const unsigned int text_data_35e4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x374c-0x3750 padding */
const unsigned int text_data_374c[1] = {0x60000000};
/* 0x3784-0x3790 padding */
const unsigned int text_data_3784[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x37a4-0x37b0 padding */
const unsigned int text_data_37a4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x382c-0x3830 padding */
const unsigned int text_data_382c[1] = {0x60000000};
/* 0x38b8-0x38c0 padding */
const unsigned int text_data_38b8[2] = {0x60000000, 0x60000000};
/* 0x3924-0x3930 padding */
const unsigned int text_data_3924[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x3cc4-0x3cd0 padding */
const unsigned int text_data_3cc4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x3e04-0x3e4c table switch table of the `bctr` at 0x3e00: entry i -> 0x3e04 + word[i]; targets 3e74 3e88 3e4c 3e54 3e5c 3e5c 3e5c 3e5c 3e5c 3e5c 3e5c 3e5c 3e9c 3e9c 3e9c 3e9c... */
const unsigned int text_data_3e04[18] = {0x00000070, 0x00000084, 0x00000048, 0x00000050, 0x00000058, 0x00000058, 0x00000058, 0x00000058, 0x00000058, 0x00000058, 0x00000058, 0x00000058, 0x00000098, 0x00000098, 0x00000098, 0x00000098, 0x00000098, 0x000000d0};
/* 0x3fb8-0x3fc0 padding */
const unsigned int text_data_3fb8[2] = {0x60000000, 0x60000000};
/* 0x425c-0x4260 padding */
const unsigned int text_data_425c[1] = {0x60000000};
/* 0x427c-0x4280 padding */
const unsigned int text_data_427c[1] = {0x60000000};
/* 0x46e4-0x46f0 padding */
const unsigned int text_data_46e4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x4714-0x4720 padding */
const unsigned int text_data_4714[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x4734-0x4740 padding */
const unsigned int text_data_4734[3] = {0x00000000, 0x00000000, 0x00000000};
/* 0x4884-0x4890 padding */
const unsigned int text_data_4884[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x49e4-0x49f0 padding */
const unsigned int text_data_49e4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x49f4-0x4a00 padding */
const unsigned int text_data_49f4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x4a04-0x4a10 padding */
const unsigned int text_data_4a04[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x4b38-0x4b40 padding */
const unsigned int text_data_4b38[2] = {0x60000000, 0x60000000};
/* 0x4eec-0x4ef0 padding */
const unsigned int text_data_4eec[1] = {0x60000000};
/* 0x4fe4-0x4ff0 padding */
const unsigned int text_data_4fe4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x5018-0x5020 padding */
const unsigned int text_data_5018[2] = {0x60000000, 0x60000000};
/* 0x51b4-0x51c0 padding */
const unsigned int text_data_51b4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x51e8-0x51f0 padding */
const unsigned int text_data_51e8[2] = {0x60000000, 0x60000000};
/* 0x5278-0x5280 padding */
const unsigned int text_data_5278[2] = {0x60000000, 0x60000000};
/* 0x52ec-0x52f0 padding */
const unsigned int text_data_52ec[1] = {0x60000000};
/* 0x5674-0x5680 padding */
const unsigned int text_data_5674[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x5698-0x56a0 padding */
const unsigned int text_data_5698[2] = {0x60000000, 0x60000000};
/* 0x5764-0x5770 padding */
const unsigned int text_data_5764[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x58ac-0x58b0 padding */
const unsigned int text_data_58ac[1] = {0x00000000};
/* 0x5d5c-0x5d60 padding */
const unsigned int text_data_5d5c[1] = {0x00000000};
/* 0x5d64-0x5d70 padding */
const unsigned int text_data_5d64[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x5f4c-0x5f50 padding */
const unsigned int text_data_5f4c[1] = {0x60000000};
/* 0x5f8c-0x5f90 padding */
const unsigned int text_data_5f8c[1] = {0x60000000};
/* 0x600c-0x6010 padding */
const unsigned int text_data_600c[1] = {0x60000000};
/* 0x6098-0x60a0 padding */
const unsigned int text_data_6098[2] = {0x60000000, 0x60000000};
/* 0x611c-0x6120 padding */
const unsigned int text_data_611c[1] = {0x60000000};
/* 0x61b8-0x61c0 padding */
const unsigned int text_data_61b8[2] = {0x60000000, 0x60000000};
/* 0x6224-0x6230 padding */
const unsigned int text_data_6224[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x69d4-0x69e0 padding */
const unsigned int text_data_69d4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x7014-0x7020 padding */
const unsigned int text_data_7014[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x74fc-0x7500 padding */
const unsigned int text_data_74fc[1] = {0x60000000};
/* 0x7568-0x7570 padding */
const unsigned int text_data_7568[2] = {0x60000000, 0x60000000};
/* 0x75e8-0x75f0 padding */
const unsigned int text_data_75e8[2] = {0x60000000, 0x60000000};
/* 0x773c-0x7740 padding */
const unsigned int text_data_773c[1] = {0x60000000};
/* 0x77d4-0x77e0 padding */
const unsigned int text_data_77d4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x7808-0x7810 padding */
const unsigned int text_data_7808[2] = {0x60000000, 0x60000000};
/* 0x7838-0x7840 padding */
const unsigned int text_data_7838[2] = {0x60000000, 0x60000000};
/* 0x7848-0x7850 padding */
const unsigned int text_data_7848[2] = {0x60000000, 0x60000000};
/* 0x7dd8-0x7de0 padding */
const unsigned int text_data_7dd8[2] = {0x60000000, 0x60000000};
/* 0x7fe8-0x7ff0 padding */
const unsigned int text_data_7fe8[2] = {0x60000000, 0x60000000};
/* 0x815c-0x8160 padding */
const unsigned int text_data_815c[1] = {0x60000000};
/* 0x8184-0x8190 padding */
const unsigned int text_data_8184[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x83b4-0x83c0 padding */
const unsigned int text_data_83b4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x83d4-0x83e0 padding */
const unsigned int text_data_83d4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x850c-0x8510 padding */
const unsigned int text_data_850c[1] = {0x60000000};
/* 0x8684-0x8690 padding */
const unsigned int text_data_8684[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x8754-0x8760 padding */
const unsigned int text_data_8754[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x879c-0x87a0 padding */
const unsigned int text_data_879c[1] = {0x60000000};
/* 0x87f8-0x8800 padding */
const unsigned int text_data_87f8[2] = {0x60000000, 0x60000000};
/* 0x881c-0x8820 padding */
const unsigned int text_data_881c[1] = {0x60000000};
/* 0x8898-0x88b8 table switch table of the `bctr` at 0x8894: entry i -> 0x8898 + word[i]; targets 9660 88b8 8940 89e4 9660 8acc 8c00 8d34 */
const unsigned int text_data_8898[8] = {0x00000dc8, 0x00000020, 0x000000a8, 0x0000014c, 0x00000dc8, 0x00000234, 0x00000368, 0x0000049c};
/* 0x8f2c-0x8f30 padding */
const unsigned int text_data_8f2c[1] = {0x60000000};
/* 0x8f58-0x8f78 table switch table of the `bctr` at 0x8f54: entry i -> 0x8f58 + word[i]; targets 9660 8f78 900c 90a4 9660 91a8 92f8 9448 */
const unsigned int text_data_8f58[8] = {0x00000708, 0x00000020, 0x000000b4, 0x0000014c, 0x00000708, 0x00000250, 0x000003a0, 0x000004f0};
/* 0x9668-0x9670 padding */
const unsigned int text_data_9668[2] = {0x00000000, 0x00000000};
/* 0x968c-0x9690 padding */
const unsigned int text_data_968c[1] = {0x60000000};
/* 0x9694-0x96a0 padding */
const unsigned int text_data_9694[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x9784-0x9790 padding */
const unsigned int text_data_9784[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x9844-0x9850 padding */
const unsigned int text_data_9844[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x9928-0x9930 padding */
const unsigned int text_data_9928[2] = {0x60000000, 0x60000000};
/* 0x9ab8-0x9ac0 padding */
const unsigned int text_data_9ab8[2] = {0x60000000, 0x60000000};
/* 0x9b84-0x9b90 padding */
const unsigned int text_data_9b84[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x9c74-0x9c80 padding */
const unsigned int text_data_9c74[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0xa108-0xa110 padding */
const unsigned int text_data_a108[2] = {0x60000000, 0x60000000};
/* 0xa4d4-0xa4e0 padding */
const unsigned int text_data_a4d4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0xa5ac-0xa5b0 padding */
const unsigned int text_data_a5ac[1] = {0x60000000};
/* 0xa8bc-0xa8c0 padding */
const unsigned int text_data_a8bc[1] = {0x60000000};
/* 0xb038-0xb040 padding */
const unsigned int text_data_b038[2] = {0x60000000, 0x60000000};
/* 0xb04c-0xb050 padding */
const unsigned int text_data_b04c[1] = {0x60000000};
/* 0xb1d4-0xb1e0 padding */
const unsigned int text_data_b1d4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0xb7e4-0xb7f0 padding */
const unsigned int text_data_b7e4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0xbbb4-0xbbc0 padding */
const unsigned int text_data_bbb4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0xbf68-0xbf70 padding */
const unsigned int text_data_bf68[2] = {0x60000000, 0x60000000};
/* 0xc078-0xc080 padding */
const unsigned int text_data_c078[2] = {0x60000000, 0x60000000};
/* 0xc158-0xc160 padding */
const unsigned int text_data_c158[2] = {0x60000000, 0x60000000};
/* 0xc708-0xc710 padding */
const unsigned int text_data_c708[2] = {0x60000000, 0x60000000};
/* 0xca9c-0xcaa0 padding */
const unsigned int text_data_ca9c[1] = {0x60000000};
/* 0xcafc-0xcb00 padding */
const unsigned int text_data_cafc[1] = {0x00000000};
