/* Millicode entries and tiny code fragments no function owns (register save/restore helpers, clipped function entries, jump-table
   case fragments), as asm. Generated by Tools/userspace/raw_emit.py; every block is byte-verified against the stock binary. */
__asm__(".text\n.globl _raw_cf70\n_raw_cf70:\n\tstfd f14,-144(r1)\n\tstfd f15,-136(r1)\n\tstfd f16,-128(r1)\n\tstfd f17,-120(r1)\n\tstfd f18,-112(r1)\n\tstfd f19,-104(r1)\n\tstfd f20,-96(r1)\n\tstfd f21,-88(r1)\n\tstfd f22,-80(r1)\n\tstfd f23,-72(r1)\n");
__asm__(".text\n.globl _raw_cfc0\n_raw_cfc0:\n\tlfd f14,-144(r1)\n\tlfd f15,-136(r1)\n\tlfd f16,-128(r1)\n\tlfd f17,-120(r1)\n\tlfd f18,-112(r1)\n\tlfd f19,-104(r1)\n\tlfd f20,-96(r1)\n\tlfd f21,-88(r1)\n\tlfd f22,-80(r1)\n\tlfd f23,-72(r1)\n");
