/* perf_2d_compositing.c - issue #44's last open item: an automated replacement for the single-session, human-driven
 * desktop-compositing baseline in Tests/performance_plan.md section 8.
 *
 * Why automate rather than repeat the manual method: that method needed a human physically at the console reading
 * Quartz Debug's Frame Meter live during each gesture (tiger-ssh's own documented limits on SSH-driven GUI
 * interaction). This file drives the same five gestures via Quartz Event Services' real, Tiger-native synthetic-
 * input API (CGPostMouseEvent/CGPostScrollWheelEvent, CGRemoteOperation.h - posts at the HID level, indistinguishable
 * to WindowServer from real hardware input) against the ALREADY-RUNNING login session - this never launches a new
 * GUI process of its own, so it does not touch the CoreDrag/bootstrap deadlock the tiger-ssh skill documents for
 * SSH-launched GUI apps.
 *
 * Caveat accepted deliberately, per the user's own call (2026-10-06): synthetic input may drive a genuinely
 * different (likely lower) redraw cadence than a real human hand on a real mouse - WindowServer could coalesce a
 * paced synthetic event stream differently than real HID interrupts. This is NOT claimed to numerically match the
 * original manual session's reported "~5-35 fps" range, and should not be compared against those numbers directly.
 * What this buys instead: a fully automated, precisely repeatable procedure - the same inputs, byte-for-byte, every
 * run - which is what a real regression gate actually needs, more than matching an old human-eyeballed number.
 *
 * Readout: Quartz Debug's Frame Meter is an ANALOG NEEDLE GAUGE (0-90 dial), not a digital counter - there is no
 * text to read, so this program cannot "parse" a value directly. It instead saves timestamped screencapture frames
 * during each gesture into a results directory; Tools/gauge_read.py (plain-stdlib PNG decoding, no PIL/numpy) reads
 * the needle's angle from each frame and converts it to a value, using a calibration derived and cross-validated
 * directly from real captures (see that file's own header). Full-screen `screencapture` costs ~1.1s/capture on this
 * hardware (confirmed by direct measurement - there is no faster non-invasive capture path on Tiger: CGDisplay-
 * CreateImage/CGWindowListCreateImage don't exist on this SDK, and CGDisplayBaseAddress needs CGDisplayCapture,
 * which would blank other apps' drawing - unacceptable on a live session), so each gesture runs long enough (10s)
 * to collect several samples despite that cost, rather than trying to catch a true instantaneous peak.
 *
 * Precondition (checked, not set up by this program): Quartz Debug running with Tools -> Show Frame Meter already
 * active, and a disposable Finder window open in LIST view on a folder with enough items to scroll (e.g. Desktop).
 * This program finds that window by name via AppleScript rather than assuming fixed screen coordinates for it.
 *
 * Usage: perf_2d_compositing OUTDIR
 *   Captures idle + 5 gesture scenarios, ~10s each, into OUTDIR/<scenario>_NN.png. Run Tools/gauge_read.py OUTDIR/*
 *   afterward to get per-scenario peak/mean values.
 * Build on the G5: gcc -arch ppc -o perf_2d_compositing perf_2d_compositing.c -framework ApplicationServices
 */
#include <ApplicationServices/ApplicationServices.h>
#include <stdio.h>
#include <stdlib.h>
#include <unistd.h>
#include <string.h>
#include <sys/wait.h>

static char g_outdir[512];

static void capture(const char *scenario, int n) {
    char path[600];
    pid_t pid;
    snprintf(path, sizeof path, "%s/%s_%02d.png", g_outdir, scenario, n);
    pid = fork();
    if (pid == 0) {
        execlp("screencapture", "screencapture", "-x", path, (char *)NULL);
        _exit(127);
    }
    waitpid(pid, NULL, 0);
}

static CGPoint cur_pos(void) {
    CGEventRef ev = CGEventCreate(NULL);
    CGPoint p = CGEventGetLocation(ev);
    CFRelease(ev);
    return p;
}

static void drag_lap(double fx, double fy, double tx, double ty, int steps, int step_us) {
    int i;
    for (i = 1; i <= steps; i++) {
        double x = fx + (tx - fx) * i / (double)steps;
        double y = fy + (ty - fy) * i / (double)steps;
        CGPostMouseEvent(CGPointMake(x, y), TRUE, 1, TRUE);
        usleep(step_us);
    }
}

/* Runs `samples` capture() calls, each preceded by `between_frames` of continuous synthetic input generated by
 * calling gesture_step(i) in a tight loop for roughly one capture interval's worth of wall-clock time - this is an
 * interleaved approximation (capture blocks for ~1.1s, during which no new input is posted), not true concurrent
 * sampling; see the file header for why a faster, non-blocking capture path isn't available on this OS. */
typedef void (*gesture_step_fn)(int tick);

static void run_scenario(const char *name, int samples, gesture_step_fn step) {
    int s, tick = 0;
    printf("scenario %s: %d samples\n", name, samples);
    for (s = 0; s < samples; s++) {
        int i;
        for (i = 0; i < 20; i++) { if (step) step(tick++); usleep(15000); }
        capture(name, s);
    }
}

/* --- per-scenario gesture step functions --- */
static double g_dragFX, g_dragFY, g_dragTX, g_dragTY;
static void step_drag(int tick) {
    int lap = tick / 20, sub = tick % 20;
    double fx = (lap % 2 == 0) ? g_dragFX : g_dragTX, fy = (lap % 2 == 0) ? g_dragFY : g_dragTY;
    double tx = (lap % 2 == 0) ? g_dragTX : g_dragFX, ty = (lap % 2 == 0) ? g_dragTY : g_dragFY;
    double x = fx + (tx - fx) * (sub + 1) / 20.0, y = fy + (ty - fy) * (sub + 1) / 20.0;
    CGPostMouseEvent(CGPointMake(x, y), TRUE, 1, TRUE);
}

static void step_scroll(int tick) {
    int dir = ((tick / 15) % 2 == 0) ? -3 : 3; /* alternate scroll direction every 15 ticks */
    CGPostScrollWheelEvent(1, dir);
}

static double g_dockY;
static void step_dock(int tick) {
    double x = 40 + (tick % 60) * 30.0; /* sweep left-to-right across the Dock, wrapping */
    CGPostMouseEvent(CGPointMake(x, g_dockY), TRUE, 1, FALSE);
}

static void step_idle(int tick) { (void)tick; }

int main(int argc, char **argv) {
    char cmd[256];
    double winL, winT, winR, winB;
    FILE *fp;

    if (argc < 2) { fprintf(stderr, "usage: perf_2d_compositing OUTDIR\n"); return 1; }
    snprintf(g_outdir, sizeof g_outdir, "%s", argv[1]);
    snprintf(cmd, sizeof cmd, "mkdir -p '%s'", g_outdir);
    system(cmd);

    /* Find the disposable test window's bounds via AppleScript rather than assume fixed coordinates. */
    fp = popen("osascript -e 'tell application \"Finder\" to get bounds of front window'", "r");
    if (!fp || fscanf(fp, "%lf, %lf, %lf, %lf", &winL, &winT, &winR, &winB) != 4) {
        fprintf(stderr, "could not read front Finder window bounds - open one first (List view, a folder with "
                        "enough items to scroll, e.g. Desktop)\n");
        if (fp) pclose(fp);
        return 1;
    }
    pclose(fp);
    printf("using Finder window bounds: %.0f,%.0f - %.0f,%.0f\n", winL, winT, winR, winB);

    /* idle baseline */
    run_scenario("idle", 5, step_idle);

    /* window open/close: repeatedly toggle a second window - counts as real compositing work each time */
    {
        int i;
        printf("scenario window_open: 5 samples\n");
        for (i = 0; i < 5; i++) {
            system("osascript -e 'tell application \"Finder\" to make new Finder window' "
                   "-e 'tell application \"Finder\" to set bounds of front window to {700,100,1000,350}' "
                   "-e 'tell application \"Finder\" to close front window' > /dev/null 2>&1");
            usleep(300000);
            capture("window_open", i);
        }
    }

    /* window drag: titlebar is ~11px above winT, centered horizontally */
    g_dragFX = (winL + winR) / 2.0; g_dragFY = winT - 11;
    g_dragTX = g_dragFX + 150; g_dragTY = g_dragFY + 100;
    CGPostMouseEvent(CGPointMake(g_dragFX, g_dragFY), TRUE, 1, FALSE);
    usleep(150000);
    CGPostMouseEvent(CGPointMake(g_dragFX, g_dragFY), TRUE, 1, TRUE);
    usleep(100000);
    run_scenario("window_drag", 10, step_drag);
    CGPostMouseEvent(CGPointMake(cur_pos().x, cur_pos().y), TRUE, 1, FALSE);
    /* put the window back roughly where it was for the resize scenario's math below */
    {
        char restoreCmd[400];
        snprintf(restoreCmd, sizeof restoreCmd,
                 "osascript -e 'tell application \"Finder\" to set bounds of front window to {%.0f,%.0f,%.0f,%.0f}'"
                 " > /dev/null 2>&1", winL, winT, winR, winB);
        system(restoreCmd);
    }

    /* window resize: drag the bottom-right corner */
    g_dragFX = winR - 8; g_dragFY = winB - 8;
    g_dragTX = g_dragFX + 150; g_dragTY = g_dragFY + 100;
    CGPostMouseEvent(CGPointMake(g_dragFX, g_dragFY), TRUE, 1, FALSE);
    usleep(150000);
    CGPostMouseEvent(CGPointMake(g_dragFX, g_dragFY), TRUE, 1, TRUE);
    usleep(100000);
    run_scenario("window_resize", 10, step_drag);
    CGPostMouseEvent(CGPointMake(cur_pos().x, cur_pos().y), TRUE, 1, FALSE);

    /* scrolling: cursor needs to be over the Finder window's content area */
    CGPostMouseEvent(CGPointMake((winL + winR) / 2.0, (winT + winB) / 2.0), TRUE, 1, FALSE);
    usleep(100000);
    run_scenario("scroll", 10, step_scroll);

    /* Dock hover: Dock sits at the very bottom of the screen */
    g_dockY = (double)(int)CGDisplayPixelsHigh(CGMainDisplayID()) - 20;
    run_scenario("dock_hover", 10, step_dock);
    CGPostMouseEvent(CGPointMake(960, 540), TRUE, 1, FALSE); /* park the cursor away from the Dock when done */

    printf("done - run: python3 Tools/gauge_read.py '%s'/*.png\n", g_outdir);
    return 0;
}
