#!/usr/bin/env python3
"""raw_emit.py SLICE STOCK_DIS RAWPREFIX OUTDIR - write the parts of __text that are not functions:
  OUTDIR/data_in_text.c   every table / alignment-padding run as `const unsigned int text_data_<addr>[]` (words read from the binary; switch offset
                          tables get their decoded targets in a comment)
  OUTDIR/raw_code.c       millicode entries and tiny code fragments as top-level asm, real mnemonics where the Tiger assembler reproduces the exact
                          machine word, `.long` (with the mnemonic in a comment) where it does not
Compiles both on the G5 and compares every emitted byte with the stock binary; writes OUTDIR/verify.txt."""
import sys, struct, re, os, subprocess
slice_f, dis, pref, out = sys.argv[1:5]; os.makedirs(out, exist_ok=True)
d = open(slice_f, 'rb').read(); E = '>'
nc = struct.unpack(E + 'I', d[16:20])[0]; q = 28; text = None
for _ in range(nc):
    c, cs = struct.unpack(E + 'II', d[q:q + 8])
    if c == 1:
        ns = struct.unpack(E + 'I', d[q + 48:q + 52])[0]; r = q + 56
        for _ in range(ns):
            nm = d[r:r + 16].rstrip(b'\0').decode(); a, sz, off = struct.unpack(E + '3I', d[r + 32:r + 44]); r += 68
            if nm == '__text': text = (a, sz, off)
    q += cs
def word(a): return struct.unpack(E + 'I', d[text[2] + a - text[0]:text[2] + a - text[0] + 4])[0]
ins = {}
for l in open(dis):
    m = re.match(r'^([0-9a-f]{8})\t(\S+)\s*(.*)$', l)
    if m: ins[int(m.group(1), 16)] = (m.group(2), m.group(3).strip())
# ---- data
n_data = 0; words_data = {}
with open(out + '/data_in_text.c', 'w') as f:
    f.write('/* Non-code words in __text (switch offset tables, alignment padding), read from the binary. Generated by Tools/userspace/raw_emit.py */\n')
    for l in open(pref + '.data.tsv'):
        s, e, kind = l.split('\t'); s = int(s, 16); e = int(e, 16); kind = kind.strip()
        w = [word(a) for a in range(s, e, 4)]; words_data[s] = w
        note = ''
        if kind == 'table' and s - 4 in ins and ins[s - 4][0] == 'bctr':
            note = ' switch table of the `bctr` at 0x%x: entry i -> 0x%x + word[i]; targets ' % (s - 4, s) + ' '.join('%x' % (s + x) for x in w[:16] if x < 0x10000) + ('...' if len(w) > 16 else '')
        f.write('/* 0x%x-0x%x %s%s */\nconst unsigned int text_data_%x[%d] = {%s};\n' % (s, e, kind, note, s, len(w), ', '.join('0x%08x' % x for x in w)))
        n_data += 1
# ---- asm
def fix_imm(op, ops):
    m = re.match(r'^(.*?)(0x[0-9a-f]+)\((r\d+)\)$', ops)
    if m and int(m.group(2), 16) >= 0x8000 and int(m.group(2), 16) <= 0xffff:
        return '%s%d(%s)' % (m.group(1), int(m.group(2), 16) - 0x10000, m.group(3))
    if op in ('addi', 'li', 'cmpwi', 'subfic', 'mulli', 'lis', 'addis'):
        parts = ops.split(','); 
        if op in ('lis', 'addis'): return ops
        v = parts[-1]
        if v.startswith('0x') and 0x8000 <= int(v, 16) <= 0xffff: parts[-1] = str(int(v, 16) - 0x10000)
        return ','.join(parts)
    return ops
def mnem(a):
    op, ops = ins[a]; ops = ops.split(';')[0].strip()
    if op == 'mfspr' and ops.endswith(',lr'): return 'mflr ' + ops.split(',')[0]
    if op == 'mtspr' and ops.startswith('lr,'): return 'mtlr ' + ops.split(',')[1]
    if op == 'mtspr' and ops.startswith('ctr,'): return 'mtctr ' + ops.split(',')[1]
    m = re.search(r'0x([0-9a-f]+)$', ops)
    if op.startswith('b') and op not in ('blr', 'bctr', 'bctrl') and m and not op.endswith('lr') and not op.endswith('ctr'):
        delta = int(m.group(1), 16) - a
        if abs(delta) > (0x1fff000 if op in ('b', 'bl') else 0x7f00): return None
        return '%s %s.%s%d' % (op, ops[:m.start()], '+' if delta >= 0 else '-', abs(delta))
    return op + ' ' + fix_imm(op, ops) if ops else op
blocks = []
for suffix in ('.mill.tsv', '.code.tsv'):   # millicode/tiny fragments and case-body code runs
    for l in open(pref + suffix):
        s, e = [int(x, 16) for x in l.split()[:2]]; blocks.append((s, e))
blocks.sort()
def asm_block(s, e, mode):
    lines = []
    for a in range(s, e, 4):
        w = word(a); op, ops = ins.get(a, ('?', ''))
        if mode == 'mn' and op not in ('.long', 'attn', '?') and mnem(a) is not None and not re.search(r'_[A-Za-z]{2,}|\.eh|[A-Za-z]\w*\.[A-Za-z]', ins[a][1]): lines.append('\\t%s\\n' % mnem(a).replace('"', '\\"'))
        else: lines.append('\\t.long 0x%08x\\t; %s %s\\n' % (w, op, ops))
    return '__asm__(".text\\n.globl _raw_%x\\n_raw_%x:\\n%s");\n' % (s, s, ''.join(lines))
def build(modes):
    with open(out + '/raw_code.c', 'w') as f:
        f.write('/* Millicode entries and tiny code fragments no function owns (register save/restore helpers, clipped function entries, jump-table\n   case fragments), as asm. Generated by Tools/userspace/raw_emit.py; every block is byte-verified against the stock binary. */\n')
        for (s, e) in blocks: f.write(asm_block(s, e, modes[(s, e)]))
modes = {b: 'mn' for b in blocks}
def compile_and_check():
    build(modes)
    subprocess.run(['scp', '-q', out + '/raw_code.c', 'G5:/tmp/raw_code.c'], check=True)
    r = subprocess.run(['ssh', 'G5', 'cd /tmp && gcc -arch ppc -w -c raw_code.c -o raw_code.o 2>&1 | head -40'], capture_output=True, text=True)
    return r.stdout
bad = set()
for it in range(6):
    msg = compile_and_check()
    lines = re.findall(r'raw_code\.c:(\d+): (?:error|Error)', msg) + re.findall(r'raw_code\.c:(\d+):', msg)
    if 'rror' not in msg and not lines: break
    # map assembler line numbers (of the C file) to blocks: each block is one C line after the 2 comment lines
    for ln in set(int(x) for x in lines):
        idx = ln - 3
        if 0 <= idx < len(blocks): modes[blocks[idx]] = 'long'
    if it == 5: print(msg)
def verify():
  global tsec
  subprocess.run(['scp', '-q', 'G5:/tmp/raw_code.o', out + '/raw_code.o'], check=True)
  o = open(out + '/raw_code.o', 'rb').read()
  nco = struct.unpack(E + 'I', o[16:20])[0]; q = 28; tsec = None; symoff = nsyms = stroff = 0
  for _ in range(nco):
      c, cs = struct.unpack(E + 'II', o[q:q + 8])
      if c == 1:
          ns = struct.unpack(E + 'I', o[q + 48:q + 52])[0]; r = q + 56
          for _ in range(ns):
              nm = o[r:r + 16].rstrip(b'\0').decode(); a, sz, off = struct.unpack(E + '3I', o[r + 32:r + 44]); r += 68
              if nm == '__text': tsec = (a, sz, off)
      elif c == 2: symoff, nsyms, stroff, _sz = struct.unpack(E + '4I', o[q + 8:q + 24])
      q += cs
  symaddr = {}
  for i in range(nsyms):
      n_strx, t, sect, desc, val = struct.unpack(E + 'IBBhI', o[symoff + 12 * i:symoff + 12 * i + 12])
      nm = o[stroff + n_strx:o.index(b'\0', stroff + n_strx)].decode()
      if nm.startswith('_raw_'): symaddr[int(nm[5:], 16)] = val
  ok = mism = 0; bads = []
  for (s, e) in blocks:
      a = symaddr.get(s)
      if a is None: mism += 1; bads.append((s, e)); continue
      ob = o[tsec[2] + a - tsec[0]: tsec[2] + a - tsec[0] + (e - s)]
      sb = b''.join(struct.pack(E + 'I', word(x)) for x in range(s, e, 4))
      if ob == sb: ok += 1
      else: mism += 1; bads.append((s, e))

  return ok, mism, bads
ok, mism, bads = verify()
if bads:
    for b in bads: modes[b] = 'long'
    compile_and_check(); ok, mism, bads = verify()
nlong = sum(1 for m in modes.values() if m == 'long')
with open(out + '/verify.txt', 'w') as f:
    f.write('data_in_text.c: %d runs, %d words (plain copies of the binary)\nraw_code.c: %d blocks assembled and compared byte-for-byte with the stock binary: %d identical, %d mismatched (%d written as .long+mnemonic comment, %d as real mnemonics)\n' % (n_data, sum(len(v) for v in words_data.values()), len(blocks), ok, mism, nlong, len(blocks) - nlong))
os.remove(out + '/raw_code.o')
print(open(out + '/verify.txt').read())
