/* Non-code words in __text (switch offset tables, alignment padding), read from the binary. Generated by Tools/userspace/raw_emit.py */
/* 0x1684-0x1690 padding */
const unsigned int text_data_1684[3] = {0x00000000, 0x00000000, 0x00000000};
/* 0x16d8-0x16e0 padding */
const unsigned int text_data_16d8[2] = {0x60000000, 0x60000000};
/* 0x1758-0x1760 padding */
const unsigned int text_data_1758[2] = {0x60000000, 0x60000000};
/* 0x1794-0x17a0 padding */
const unsigned int text_data_1794[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x17b8-0x17c0 padding */
const unsigned int text_data_17b8[2] = {0x60000000, 0x60000000};
/* 0x1814-0x1820 padding */
const unsigned int text_data_1814[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x1854-0x1860 padding */
const unsigned int text_data_1854[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x18bc-0x18c0 padding */
const unsigned int text_data_18bc[1] = {0x60000000};
/* 0x18f4-0x1900 padding */
const unsigned int text_data_18f4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x194c-0x1950 padding */
const unsigned int text_data_194c[1] = {0x60000000};
/* 0x199c-0x19c8 table switch table of the `bctr` at 0x1998: entry i -> 0x199c + word[i]; targets 19f8 19f0 19d0 1a00 1a18 19c8 1a08 1a10 19e8 19e0 19d8 */
const unsigned int text_data_199c[11] = {0x0000005c, 0x00000054, 0x00000034, 0x00000064, 0x0000007c, 0x0000002c, 0x0000006c, 0x00000074, 0x0000004c, 0x00000044, 0x0000003c};
/* 0x1b74-0x1b80 padding */
const unsigned int text_data_1b74[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x1b94-0x1ba0 padding */
const unsigned int text_data_1b94[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x1c0c-0x1c10 padding */
const unsigned int text_data_1c0c[1] = {0x60000000};
/* 0x1c38-0x1c40 padding */
const unsigned int text_data_1c38[2] = {0x60000000, 0x60000000};
/* 0x1d78-0x1d80 padding */
const unsigned int text_data_1d78[2] = {0x60000000, 0x60000000};
/* 0x1d88-0x1d90 padding */
const unsigned int text_data_1d88[2] = {0x60000000, 0x60000000};
/* 0x1ecc-0x1ed0 padding */
const unsigned int text_data_1ecc[1] = {0x60000000};
/* 0x1fcc-0x1fd0 padding */
const unsigned int text_data_1fcc[1] = {0x60000000};
/* 0x20a8-0x20b0 padding */
const unsigned int text_data_20a8[2] = {0x60000000, 0x60000000};
/* 0x20c8-0x20d0 padding */
const unsigned int text_data_20c8[2] = {0x60000000, 0x60000000};
/* 0x20dc-0x20e0 padding */
const unsigned int text_data_20dc[1] = {0x60000000};
/* 0x2128-0x2130 padding */
const unsigned int text_data_2128[2] = {0x60000000, 0x60000000};
/* 0x2144-0x2150 padding */
const unsigned int text_data_2144[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2164-0x2170 padding */
const unsigned int text_data_2164[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x21ac-0x21b0 padding */
const unsigned int text_data_21ac[1] = {0x60000000};
/* 0x21cc-0x21d0 padding */
const unsigned int text_data_21cc[1] = {0x60000000};
/* 0x21e8-0x21f0 padding */
const unsigned int text_data_21e8[2] = {0x60000000, 0x60000000};
/* 0x21f8-0x2200 padding */
const unsigned int text_data_21f8[2] = {0x60000000, 0x60000000};
/* 0x2268-0x2270 padding */
const unsigned int text_data_2268[2] = {0x60000000, 0x60000000};
/* 0x2288-0x2290 padding */
const unsigned int text_data_2288[2] = {0x60000000, 0x60000000};
/* 0x22b8-0x22c0 padding */
const unsigned int text_data_22b8[2] = {0x60000000, 0x60000000};
/* 0x22c8-0x22d0 padding */
const unsigned int text_data_22c8[2] = {0x60000000, 0x60000000};
/* 0x2414-0x2420 padding */
const unsigned int text_data_2414[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2484-0x2490 padding */
const unsigned int text_data_2484[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x24c4-0x24d0 padding */
const unsigned int text_data_24c4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2604-0x2610 padding */
const unsigned int text_data_2604[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x269c-0x26a0 padding */
const unsigned int text_data_269c[1] = {0x60000000};
/* 0x2748-0x2750 padding */
const unsigned int text_data_2748[2] = {0x60000000, 0x60000000};
/* 0x28dc-0x28e0 padding */
const unsigned int text_data_28dc[1] = {0x60000000};
/* 0x2994-0x29a0 padding */
const unsigned int text_data_2994[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2b8c-0x2b90 padding */
const unsigned int text_data_2b8c[1] = {0x60000000};
/* 0x2ca4-0x2cb0 padding */
const unsigned int text_data_2ca4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2cc8-0x2cd0 padding */
const unsigned int text_data_2cc8[2] = {0x60000000, 0x60000000};
/* 0x2d04-0x2d10 padding */
const unsigned int text_data_2d04[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2d84-0x2d90 padding */
const unsigned int text_data_2d84[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x2d9c-0x2da0 padding */
const unsigned int text_data_2d9c[1] = {0x60000000};
/* 0x32b4-0x32c0 padding */
const unsigned int text_data_32b4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x3428-0x3430 padding */
const unsigned int text_data_3428[2] = {0x60000000, 0x60000000};
/* 0x348c-0x3490 padding */
const unsigned int text_data_348c[1] = {0x60000000};
/* 0x34d8-0x34e0 padding */
const unsigned int text_data_34d8[2] = {0x60000000, 0x60000000};
/* 0x39c8-0x39d0 padding */
const unsigned int text_data_39c8[2] = {0x60000000, 0x60000000};
/* 0x3d2c-0x3d30 padding */
const unsigned int text_data_3d2c[1] = {0x60000000};
/* 0x3da4-0x3db0 padding */
const unsigned int text_data_3da4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x3e5c-0x3e60 padding */
const unsigned int text_data_3e5c[1] = {0x60000000};
/* 0x3e98-0x3ea0 padding */
const unsigned int text_data_3e98[2] = {0x60000000, 0x60000000};
/* 0x3f2c-0x3f30 padding */
const unsigned int text_data_3f2c[1] = {0x60000000};
/* 0x3f64-0x3f70 padding */
const unsigned int text_data_3f64[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x401c-0x4020 padding */
const unsigned int text_data_401c[1] = {0x60000000};
/* 0x4078-0x4080 padding */
const unsigned int text_data_4078[2] = {0x60000000, 0x60000000};
/* 0x412c-0x4130 padding */
const unsigned int text_data_412c[1] = {0x60000000};
/* 0x4144-0x4150 padding */
const unsigned int text_data_4144[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x41c8-0x41d0 padding */
const unsigned int text_data_41c8[2] = {0x60000000, 0x60000000};
/* 0x4258-0x4260 padding */
const unsigned int text_data_4258[2] = {0x60000000, 0x60000000};
/* 0x42e8-0x42f0 padding */
const unsigned int text_data_42e8[2] = {0x60000000, 0x60000000};
/* 0x4384-0x4390 padding */
const unsigned int text_data_4384[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x439c-0x43a0 padding */
const unsigned int text_data_439c[1] = {0x60000000};
/* 0x443c-0x4440 padding */
const unsigned int text_data_443c[1] = {0x60000000};
/* 0x44c8-0x44d0 padding */
const unsigned int text_data_44c8[2] = {0x60000000, 0x60000000};
/* 0x45f8-0x4600 padding */
const unsigned int text_data_45f8[2] = {0x60000000, 0x60000000};
/* 0x46ac-0x46b0 padding */
const unsigned int text_data_46ac[1] = {0x60000000};
/* 0x46e4-0x46f0 padding */
const unsigned int text_data_46e4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x4cb4-0x4cc0 padding */
const unsigned int text_data_4cb4[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x520c-0x5210 padding */
const unsigned int text_data_520c[1] = {0x60000000};
/* 0x5558-0x5560 padding */
const unsigned int text_data_5558[2] = {0x60000000, 0x60000000};
/* 0x556c-0x5570 padding */
const unsigned int text_data_556c[1] = {0x60000000};
/* 0x5594-0x55a0 padding */
const unsigned int text_data_5594[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x58ac-0x58b0 padding */
const unsigned int text_data_58ac[1] = {0x60000000};
/* 0x5964-0x5970 padding */
const unsigned int text_data_5964[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x5d84-0x5d90 padding */
const unsigned int text_data_5d84[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0x5fc8-0x5fd0 padding */
const unsigned int text_data_5fc8[2] = {0x60000000, 0x60000000};
/* 0x654c-0x6550 padding */
const unsigned int text_data_654c[1] = {0x60000000};
/* 0x81d8-0x81e0 padding */
const unsigned int text_data_81d8[2] = {0x60000000, 0x60000000};
/* 0x823c-0x8240 padding */
const unsigned int text_data_823c[1] = {0x60000000};
/* 0x825c-0x8260 padding */
const unsigned int text_data_825c[1] = {0x60000000};
/* 0x8678-0x8680 padding */
const unsigned int text_data_8678[2] = {0x60000000, 0x60000000};
/* 0xa56c-0xa570 padding */
const unsigned int text_data_a56c[1] = {0x60000000};
/* 0xa594-0xa5a0 padding */
const unsigned int text_data_a594[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0xa758-0xa760 padding */
const unsigned int text_data_a758[2] = {0x60000000, 0x60000000};
/* 0xa904-0xa910 padding */
const unsigned int text_data_a904[3] = {0x60000000, 0x60000000, 0x60000000};
/* 0xad28-0xad30 padding */
const unsigned int text_data_ad28[2] = {0x60000000, 0x60000000};
/* 0xaec8-0xaed0 padding */
const unsigned int text_data_aec8[2] = {0x60000000, 0x60000000};
/* 0xb618-0xb620 padding */
const unsigned int text_data_b618[2] = {0x60000000, 0x60000000};
/* 0xb7c8-0xb7d0 padding */
const unsigned int text_data_b7c8[2] = {0x60000000, 0x60000000};
/* 0xba6c-0xba70 padding */
const unsigned int text_data_ba6c[1] = {0x60000000};
/* 0xba8c-0xba90 padding */
const unsigned int text_data_ba8c[1] = {0x60000000};
/* 0xc878-0xc880 padding */
const unsigned int text_data_c878[2] = {0x60000000, 0x60000000};
