/* Millicode entries and tiny code fragments no function owns (register save/restore helpers, clipped function entries, jump-table
   case fragments), as asm. Generated by Tools/userspace/raw_emit.py; every block is byte-verified against the stock binary. */
__asm__(".text\n.globl _raw_55a0\n_raw_55a0:\n\tmfcr r2\n");
__asm__(".text\n.globl _raw_c948\n_raw_c948:\n\tstfd f14,-144(r1)\n\tstfd f15,-136(r1)\n\tstfd f16,-128(r1)\n");
__asm__(".text\n.globl _raw_c998\n_raw_c998:\n\tlfd f14,-144(r1)\n\tlfd f15,-136(r1)\n\tlfd f16,-128(r1)\n");
