/* GENERATED by Tools/gen_layout_checks.py - do not edit. Compile-time layout checks (see that script). */
#define protected public
#define private public
#include "../Headers/ATIRadeonX1000.h"
#include "../Headers/IOATIR500Accelerator.h"
#include "../Headers/IOATIR500GLContext.h"
#include "../Headers/IOATIR5002DContext.h"
#include "../Headers/IOATIR500DVDContext.h"
#include "../Headers/IOATIR500Surface.h"
#include "../Headers/IOATIR500Shared.h"
#include "../Headers/ATIR500Surface.h"
#include "../Headers/ATIR500GLContext.h"
#include "../Headers/ATIR5002DContext.h"
#include "../Headers/ATIR500DVDContext.h"
#include "../Headers/ATIR500Memory.h"
#include "../Headers/ATIRadeonX1000Types.h"
#undef protected
#undef private

#define LAYOUT_CHECK(name, expr) typedef char layout_check_##name[(expr) ? 1 : -1]

LAYOUT_CHECK(size_IOUserClient, sizeof(IOUserClient) == 0x78);
LAYOUT_CHECK(size_IOAccelerator, sizeof(IOAccelerator) == 0x50);
LAYOUT_CHECK(size_ATIR5002DContext, sizeof(ATIR5002DContext) == 0x12c);
LAYOUT_CHECK(size_ATIR500DVDContext, sizeof(ATIR500DVDContext) == 0x1e0);
LAYOUT_CHECK(size_ATIR500GLContext, sizeof(ATIR500GLContext) == 0x690);
LAYOUT_CHECK(size_ATIR500Memory, sizeof(ATIR500Memory) == 0x14);
LAYOUT_CHECK(size_ATIR500Surface, sizeof(ATIR500Surface) == 0xdbc);
LAYOUT_CHECK(size_ATIRadeonX1000, sizeof(ATIRadeonX1000) == 0xc60);
LAYOUT_CHECK(size_IOATIR500Shared, sizeof(IOATIR500Shared) == 0x28);
LAYOUT_CHECK(off1_ATIR500GLContext_textureSlotArray, __builtin_offsetof(ATIR500GLContext, textureSlotArray) == 0x2a4);
LAYOUT_CHECK(off2_ATIR500GLContext_transferBufferSlot, __builtin_offsetof(ATIR500GLContext, transferBufferSlot) == 0x328);
LAYOUT_CHECK(off3_ATIR500GLContext_secondaryTextureSlotA, __builtin_offsetof(ATIR500GLContext, secondaryTextureSlotA) == 0x338);
LAYOUT_CHECK(off4_ATIR500GLContext_secondaryTextureSlotB, __builtin_offsetof(ATIR500GLContext, secondaryTextureSlotB) == 0x348);
LAYOUT_CHECK(off5_ATIR500GLContext_scissorY, __builtin_offsetof(ATIR500GLContext, scissorY) == 0x354);
LAYOUT_CHECK(off6_ATIR500GLContext_scissorX, __builtin_offsetof(ATIR500GLContext, scissorX) == 0x358);
LAYOUT_CHECK(off7_ATIR500GLContext_someUnitIndex, __builtin_offsetof(ATIR500GLContext, someUnitIndex) == 0x35c);
LAYOUT_CHECK(off8_ATIR500GLContext_attachmentCount, __builtin_offsetof(ATIR500GLContext, attachmentCount) == 0x3a8);
LAYOUT_CHECK(off9_ATIR500GLContext_altUnitFormat, __builtin_offsetof(ATIR500GLContext, altUnitFormat) == 0x3aa);
LAYOUT_CHECK(off10_ATIR500GLContext_altUnitSelector, __builtin_offsetof(ATIR500GLContext, altUnitSelector) == 0x3b2);
LAYOUT_CHECK(off11_ATIR500GLContext_perUnitTextureArray, __builtin_offsetof(ATIR500GLContext, perUnitTextureArray) == 0x3f0);
LAYOUT_CHECK(off12_ATIRadeonX1000_deviceActiveFlag, __builtin_offsetof(ATIRadeonX1000, deviceActiveFlag) == 0x80);
LAYOUT_CHECK(off13_ATIRadeonX1000__unknown_0x224, __builtin_offsetof(ATIRadeonX1000, _unknown_0x224) == 0x224);
LAYOUT_CHECK(off14_ATIRadeonX1000__unknown_0x228, __builtin_offsetof(ATIRadeonX1000, _unknown_0x228) == 0x228);
LAYOUT_CHECK(off15_ATIRadeonX1000__unknown_0x22c, __builtin_offsetof(ATIRadeonX1000, _unknown_0x22c) == 0x22c);
LAYOUT_CHECK(off16_ATIRadeonX1000_pendingTimeStamp, __builtin_offsetof(ATIRadeonX1000, pendingTimeStamp) == 0x234);
LAYOUT_CHECK(off17_ATIRadeonX1000_scratchHeader, __builtin_offsetof(ATIRadeonX1000, scratchHeader) == 0x238);
LAYOUT_CHECK(off18_ATIRadeonX1000_cachedBufferSizeThreshold, __builtin_offsetof(ATIRadeonX1000, cachedBufferSizeThreshold) == 0x5c8);
LAYOUT_CHECK(off19_ATIRadeonX1000_freeBufferListHead, __builtin_offsetof(ATIRadeonX1000, freeBufferListHead) == 0x5cc);
LAYOUT_CHECK(off20_ATIRadeonX1000_freeBufferListTail, __builtin_offsetof(ATIRadeonX1000, freeBufferListTail) == 0x5d0);
LAYOUT_CHECK(off21_ATIRadeonX1000_freeBufferListCount, __builtin_offsetof(ATIRadeonX1000, freeBufferListCount) == 0x5d4);
LAYOUT_CHECK(off22_ATIRadeonX1000_cachedBufferSizeThresholdB, __builtin_offsetof(ATIRadeonX1000, cachedBufferSizeThresholdB) == 0x5d8);
LAYOUT_CHECK(off23_ATIRadeonX1000_dirtyTextureListHead, __builtin_offsetof(ATIRadeonX1000, dirtyTextureListHead) == 0x600);
LAYOUT_CHECK(off24_ATIRadeonX1000_secondDirtyListHead, __builtin_offsetof(ATIRadeonX1000, secondDirtyListHead) == 0x69c);
LAYOUT_CHECK(off25_ATIRadeonX1000_dataBufferByteAccumulator, __builtin_offsetof(ATIRadeonX1000, dataBufferByteAccumulator) == 0x70c);
LAYOUT_CHECK(off26_ATIRadeonX1000_commandLock, __builtin_offsetof(ATIRadeonX1000, commandLock) == 0x840);
LAYOUT_CHECK(off27_ATIRadeonX1000_idctSubmitBaseCounter, __builtin_offsetof(ATIRadeonX1000, idctSubmitBaseCounter) == 0x854);
LAYOUT_CHECK(off28_ATIRadeonX1000_mmioBase, __builtin_offsetof(ATIRadeonX1000, mmioBase) == 0x860);
LAYOUT_CHECK(off29_ATIRadeonX1000_clientMemoryDescriptorType0, __builtin_offsetof(ATIRadeonX1000, clientMemoryDescriptorType0) == 0x8d8);
LAYOUT_CHECK(off30_ATIRadeonX1000_mainRingCursor, __builtin_offsetof(ATIRadeonX1000, mainRingCursor) == 0x918);
LAYOUT_CHECK(off31_ATIRadeonX1000_idctRingCursor, __builtin_offsetof(ATIRadeonX1000, idctRingCursor) == 0x930);
LAYOUT_CHECK(off32_VendorCommandDescriptor_pendingBufferStart, __builtin_offsetof(VendorCommandDescriptor, pendingBufferStart) == 0x0);
LAYOUT_CHECK(off33_VendorCommandDescriptor_pendingBufferOffset, __builtin_offsetof(VendorCommandDescriptor, pendingBufferOffset) == 0x4);
LAYOUT_CHECK(off34_VendorCommandDescriptor_pendingDwordCount, __builtin_offsetof(VendorCommandDescriptor, pendingDwordCount) == 0x8);
LAYOUT_CHECK(off35_VendorCommandDescriptor_finalRecordCursor, __builtin_offsetof(VendorCommandDescriptor, finalRecordCursor) == 0xc);
LAYOUT_CHECK(off36_VendorCommandBufferHeader_chainLinkOrGeneration, __builtin_offsetof(VendorCommandBufferHeader, chainLinkOrGeneration) == 0x1c);
LAYOUT_CHECK(off37_VendorCommandBufferHeader_initialSizeOrFlags, __builtin_offsetof(VendorCommandBufferHeader, initialSizeOrFlags) == 0x40);
LAYOUT_CHECK(off38_VendorContextBufferHeader_capacityField, __builtin_offsetof(VendorContextBufferHeader, capacityField) == 0x10);
LAYOUT_CHECK(off39_VendorContextBufferHeader__reserved2, __builtin_offsetof(VendorContextBufferHeader, _reserved2) == 0x14);
LAYOUT_CHECK(off40_VendorContextBufferHeader_formatTag, __builtin_offsetof(VendorContextBufferHeader, formatTag) == 0x1c);
LAYOUT_CHECK(off41_VendorTextureBuffer_memoryDescriptor, __builtin_offsetof(VendorTextureBuffer, memoryDescriptor) == 0x08);
LAYOUT_CHECK(off42_VendorTextureBuffer_gartMapping, __builtin_offsetof(VendorTextureBuffer, gartMapping) == 0x10);
LAYOUT_CHECK(off43_VendorTextureBuffer_surfaceOrFormatInfo, __builtin_offsetof(VendorTextureBuffer, surfaceOrFormatInfo) == 0x24);
LAYOUT_CHECK(off44_VendorTextureBuffer_listNext, __builtin_offsetof(VendorTextureBuffer, listNext) == 0x28);
LAYOUT_CHECK(off45_VendorTextureBuffer_streamListNext, __builtin_offsetof(VendorTextureBuffer, streamListNext) == 0x3c);
LAYOUT_CHECK(off46_VendorTextureBuffer_transferBufferFlag, __builtin_offsetof(VendorTextureBuffer, transferBufferFlag) == 0x48);
LAYOUT_CHECK(off47_VendorTextureBuffer_poolSizeClass, __builtin_offsetof(VendorTextureBuffer, poolSizeClass) == 0x50);
LAYOUT_CHECK(off48_VendorTextureBuffer_linkedBuffer, __builtin_offsetof(VendorTextureBuffer, linkedBuffer) == 0x54);
LAYOUT_CHECK(off49_VendorTextureBuffer_generationTag, __builtin_offsetof(VendorTextureBuffer, generationTag) == 0x5c);
LAYOUT_CHECK(off50_VendorTransferBuffer_realBackingFlag, __builtin_offsetof(VendorTransferBuffer, realBackingFlag) == 0x04);
LAYOUT_CHECK(off51_VendorTransferBuffer_gartMappedPointer, __builtin_offsetof(VendorTransferBuffer, gartMappedPointer) == 0x14);
LAYOUT_CHECK(off52_VendorTransferBuffer_listNext, __builtin_offsetof(VendorTransferBuffer, listNext) == 0x3c);
LAYOUT_CHECK(off53_VendorTransferBuffer_poolSizeClass, __builtin_offsetof(VendorTransferBuffer, poolSizeClass) == 0x50);
LAYOUT_CHECK(off54_VendorTransferBuffer_generationTag, __builtin_offsetof(VendorTransferBuffer, generationTag) == 0x5c);
LAYOUT_CHECK(off55_ATIR500SurfaceBuffer_gpuBaseAddress, __builtin_offsetof(ATIR500SurfaceBuffer, gpuBaseAddress) == 0x08);
LAYOUT_CHECK(off56_ATIR500SurfaceBuffer_width, __builtin_offsetof(ATIR500SurfaceBuffer, width) == 0x14);
LAYOUT_CHECK(off57_ATIR500SurfaceBuffer_bytesPerRow, __builtin_offsetof(ATIR500SurfaceBuffer, bytesPerRow) == 0x16);
LAYOUT_CHECK(off58_ATIR500SurfaceBuffer_heightOrRows, __builtin_offsetof(ATIR500SurfaceBuffer, heightOrRows) == 0x1c);
LAYOUT_CHECK(off59_ATIR500SurfaceBuffer_extra1e, __builtin_offsetof(ATIR500SurfaceBuffer, extra1e) == 0x1e);
LAYOUT_CHECK(off60_ATIR500SurfaceBuffer_basePitch, __builtin_offsetof(ATIR500SurfaceBuffer, basePitch) == 0x20);
LAYOUT_CHECK(off61_ATIR500SurfaceBuffer_backingStoreHandle, __builtin_offsetof(ATIR500SurfaceBuffer, backingStoreHandle) == 0x24);
LAYOUT_CHECK(off62_ATIR500SurfaceBuffer_hzBlockField, __builtin_offsetof(ATIR500SurfaceBuffer, hzBlockField) == 0x28);
LAYOUT_CHECK(off63_ATIR500SurfaceBuffer_hzBlockExtra, __builtin_offsetof(ATIR500SurfaceBuffer, hzBlockExtra) == 0x2c);
LAYOUT_CHECK(off64_ATIR500SurfaceBuffer_hzBlockCountField, __builtin_offsetof(ATIR500SurfaceBuffer, hzBlockCountField) == 0x30);
LAYOUT_CHECK(off65_ATIR500SurfaceBuffer_zbBandwidthEligible, __builtin_offsetof(ATIR500SurfaceBuffer, zbBandwidthEligible) == 0x34);
LAYOUT_CHECK(off66_ATIR500SurfaceBuffer_hyperZEligible, __builtin_offsetof(ATIR500SurfaceBuffer, hyperZEligible) == 0x35);
LAYOUT_CHECK(off67_ATIR500SurfaceBuffer_fsaaResolvedFlag, __builtin_offsetof(ATIR500SurfaceBuffer, fsaaResolvedFlag) == 0x36);
LAYOUT_CHECK(off68_ATIR500SurfaceBuffer_tilingConfigByte0, __builtin_offsetof(ATIR500SurfaceBuffer, tilingConfigByte0) == 0x38);
LAYOUT_CHECK(off69_ATIR500SurfaceBuffer_tilingConfigByte1, __builtin_offsetof(ATIR500SurfaceBuffer, tilingConfigByte1) == 0x39);
LAYOUT_CHECK(off70_ATIR500SurfaceBuffer_formatTableIndex, __builtin_offsetof(ATIR500SurfaceBuffer, formatTableIndex) == 0x3a);
LAYOUT_CHECK(off71_ATIR500SurfaceBuffer_formatSubShift, __builtin_offsetof(ATIR500SurfaceBuffer, formatSubShift) == 0x3b);
LAYOUT_CHECK(off72_ATIR500SurfaceBuffer_tilingDegreeBits, __builtin_offsetof(ATIR500SurfaceBuffer, tilingDegreeBits) == 0x3c);
LAYOUT_CHECK(off73_ATIR500SurfaceBuffer_mipOffsets, __builtin_offsetof(ATIR500SurfaceBuffer, mipOffsets) == 0x40);
LAYOUT_CHECK(off74_AtiFormatInfoEntry_selfIndex, __builtin_offsetof(AtiFormatInfoEntry, selfIndex) == 0x00);
LAYOUT_CHECK(off75_AtiFormatInfoEntry_sharedConst1, __builtin_offsetof(AtiFormatInfoEntry, sharedConst1) == 0x04);
LAYOUT_CHECK(off76_AtiFormatInfoEntry_field08, __builtin_offsetof(AtiFormatInfoEntry, field08) == 0x08);
LAYOUT_CHECK(off77_AtiFormatInfoEntry_fieldDC, __builtin_offsetof(AtiFormatInfoEntry, fieldDC) == 0x0c);
LAYOUT_CHECK(off78_AtiFormatInfoEntry_fieldE0, __builtin_offsetof(AtiFormatInfoEntry, fieldE0) == 0x10);
LAYOUT_CHECK(off79_AtiFormatInfoEntry_fieldE4, __builtin_offsetof(AtiFormatInfoEntry, fieldE4) == 0x14);
LAYOUT_CHECK(off80_AtiFormatInfoEntry_sharedConst2, __builtin_offsetof(AtiFormatInfoEntry, sharedConst2) == 0x18);
LAYOUT_CHECK(off81_register_tracking_state_sc_edgerule, __builtin_offsetof(register_tracking_state, sc_edgerule) == 0x00);
LAYOUT_CHECK(off82_register_tracking_state_sc_screendoor, __builtin_offsetof(register_tracking_state, sc_screendoor) == 0x04);
LAYOUT_CHECK(off83_register_tracking_state_gb_aa_config, __builtin_offsetof(register_tracking_state, gb_aa_config) == 0x0c);
LAYOUT_CHECK(off84_register_tracking_state_sc_hyperz_en, __builtin_offsetof(register_tracking_state, sc_hyperz_en) == 0x14);
LAYOUT_CHECK(off85_register_tracking_state_zb_bw_cntl, __builtin_offsetof(register_tracking_state, zb_bw_cntl) == 0x18);
LAYOUT_CHECK(off86_register_tracking_state_zb_zstencilcntl, __builtin_offsetof(register_tracking_state, zb_zstencilcntl) == 0x1c);
LAYOUT_CHECK(off87_register_tracking_state_vap_cntl_status, __builtin_offsetof(register_tracking_state, vap_cntl_status) == 0x20);
LAYOUT_CHECK(off88_register_tracking_state_vap_clip_cntl, __builtin_offsetof(register_tracking_state, vap_clip_cntl) == 0x24);
LAYOUT_CHECK(off89_register_tracking_state_vap_vte_cntl, __builtin_offsetof(register_tracking_state, vap_vte_cntl) == 0x28);
LAYOUT_CHECK(off90_register_tracking_state_su_cull_mode, __builtin_offsetof(register_tracking_state, su_cull_mode) == 0x2c);
LAYOUT_CHECK(off91_register_tracking_state_rb3d_dither_ctl, __builtin_offsetof(register_tracking_state, rb3d_dither_ctl) == 0x30);
LAYOUT_CHECK(off92_register_tracking_state_vap_out_vtx_fmt_0, __builtin_offsetof(register_tracking_state, vap_out_vtx_fmt_0) == 0x3c);
LAYOUT_CHECK(off93_register_tracking_state_vap_out_vtx_fmt_1, __builtin_offsetof(register_tracking_state, vap_out_vtx_fmt_1) == 0x40);
LAYOUT_CHECK(off94_register_tracking_state_vap_vtx_size, __builtin_offsetof(register_tracking_state, vap_vtx_size) == 0x44);
LAYOUT_CHECK(off95_register_tracking_state_vap_prog_stream_cntl_0, __builtin_offsetof(register_tracking_state, vap_prog_stream_cntl_0) == 0x48);
LAYOUT_CHECK(off96_register_tracking_state_vap_prog_stream_cntl_ext_0, __builtin_offsetof(register_tracking_state, vap_prog_stream_cntl_ext_0) == 0x4c);
LAYOUT_CHECK(off97_register_tracking_state_zb_cntl, __builtin_offsetof(register_tracking_state, zb_cntl) == 0x50);
LAYOUT_CHECK(off98_register_tracking_state_fg_fog_blend, __builtin_offsetof(register_tracking_state, fg_fog_blend) == 0x54);
LAYOUT_CHECK(off99_register_tracking_state_fg_alpha_func, __builtin_offsetof(register_tracking_state, fg_alpha_func) == 0x58);
LAYOUT_CHECK(off100_register_tracking_state_ga_poly_mode, __builtin_offsetof(register_tracking_state, ga_poly_mode) == 0x5c);
LAYOUT_CHECK(off101_register_tracking_state_rb3d_blendcntl, __builtin_offsetof(register_tracking_state, rb3d_blendcntl) == 0x60);
LAYOUT_CHECK(off102_register_tracking_state_ga_color_control, __builtin_offsetof(register_tracking_state, ga_color_control) == 0x64);
LAYOUT_CHECK(off103_register_tracking_state_tx_enable, __builtin_offsetof(register_tracking_state, tx_enable) == 0x6c);
LAYOUT_CHECK(off104_register_tracking_state_gb_ps3_enable, __builtin_offsetof(register_tracking_state, gb_ps3_enable) == 0x70);
LAYOUT_CHECK(off105_register_tracking_state_ga_us_vector, __builtin_offsetof(register_tracking_state, ga_us_vector) == 0x74);
LAYOUT_CHECK(off106_register_tracking_state_us_fc_ctrl, __builtin_offsetof(register_tracking_state, us_fc_ctrl) == 0x88);
LAYOUT_CHECK(off107_register_tracking_state_us_pixsize, __builtin_offsetof(register_tracking_state, us_pixsize) == 0x8c);
LAYOUT_CHECK(off108_register_tracking_state_us_code_range, __builtin_offsetof(register_tracking_state, us_code_range) == 0x90);
LAYOUT_CHECK(off109_register_tracking_state_us_code_offset, __builtin_offsetof(register_tracking_state, us_code_offset) == 0x94);
LAYOUT_CHECK(off110_register_tracking_state_us_code_addr, __builtin_offsetof(register_tracking_state, us_code_addr) == 0x98);
LAYOUT_CHECK(off111_register_tracking_state_us_out_fmt_0, __builtin_offsetof(register_tracking_state, us_out_fmt_0) == 0x9c);
LAYOUT_CHECK(off112_register_tracking_state_rs_inst_count, __builtin_offsetof(register_tracking_state, rs_inst_count) == 0xa0);
LAYOUT_CHECK(off113_register_tracking_state_rs_inst_0, __builtin_offsetof(register_tracking_state, rs_inst_0) == 0xa4);
LAYOUT_CHECK(off114_register_tracking_state_rs_ip_0, __builtin_offsetof(register_tracking_state, rs_ip_0) == 0xa8);
LAYOUT_CHECK(off115_register_tracking_state_tx_offset, __builtin_offsetof(register_tracking_state, tx_offset) == 0xac);
LAYOUT_CHECK(off116_sATIDVDIDCTInfo_submitCookie, __builtin_offsetof(sATIDVDIDCTInfo, submitCookie) == 0x7c);
LAYOUT_CHECK(off117_sATIDVDIDCTInfo_hwAccelerator, __builtin_offsetof(sATIDVDIDCTInfo, hwAccelerator) == 0x8c);
LAYOUT_CHECK(off118_sATIDVDIDCTInfo_surfaceInfo, __builtin_offsetof(sATIDVDIDCTInfo, surfaceInfo) == 0xf8);
LAYOUT_CHECK(off119_sATIDVDIDCTInfo_lastSubmittedTag, __builtin_offsetof(sATIDVDIDCTInfo, lastSubmittedTag) == 0x150);
LAYOUT_CHECK(off120_sATIDVDIDCTInfo_lastConsumedTagLuma, __builtin_offsetof(sATIDVDIDCTInfo, lastConsumedTagStream0) == 0x154);
LAYOUT_CHECK(off121_sATIDVDIDCTInfo_lumaBufferAField_0x164, __builtin_offsetof(sATIDVDIDCTInfo, stream0BufferAField_0x164) == 0x164);
LAYOUT_CHECK(off122_sATIDVDIDCTInfo_lumaBufferA, __builtin_offsetof(sATIDVDIDCTInfo, stream0BufferA) == 0x168);
LAYOUT_CHECK(off123_sATIDVDIDCTInfo_lumaBufferB, __builtin_offsetof(sATIDVDIDCTInfo, stream0BufferB) == 0x184);
LAYOUT_CHECK(off124_sATIDVDIDCTInfo_chromaBufferAField_0x1a0, __builtin_offsetof(sATIDVDIDCTInfo, stream1BufferAField_0x1a0) == 0x1a0);
LAYOUT_CHECK(off125_sATIDVDIDCTInfo_chromaBufferA, __builtin_offsetof(sATIDVDIDCTInfo, stream1BufferA) == 0x1a4);
LAYOUT_CHECK(off126_sATIDVDIDCTInfo_chromaBufferB, __builtin_offsetof(sATIDVDIDCTInfo, stream1BufferB) == 0x1c0);
LAYOUT_CHECK(off127_sATIDVDIDCTParams_chromaFlag, __builtin_offsetof(sATIDVDIDCTParams, fieldPictureFlag) == 0x00);
LAYOUT_CHECK(off128_sATIDVDIDCTParams_fieldFlag, __builtin_offsetof(sATIDVDIDCTParams, bottomFieldFlag) == 0x04);
LAYOUT_CHECK(off129_sATIDVDIDCTParams_destPlaneIndex, __builtin_offsetof(sATIDVDIDCTParams, destPlaneIndex) == 0x08);
LAYOUT_CHECK(off130_sATIDVDIDCTParams_planeSelector, __builtin_offsetof(sATIDVDIDCTParams, planeSelector) == 0x0c);
LAYOUT_CHECK(off131_sATIDVDIDCTParams_dmaByteCount, __builtin_offsetof(sATIDVDIDCTParams, dmaDwordCount) == 0x10);
LAYOUT_CHECK(off132_sATIDVDIDCTParams_idctCoeffAddr14, __builtin_offsetof(sATIDVDIDCTParams, engineFlagWord) == 0x14);
LAYOUT_CHECK(off133_sATIDVDIDCTParams_idctCoeffAddr18, __builtin_offsetof(sATIDVDIDCTParams, planeModeWord) == 0x18);
LAYOUT_CHECK(off134_sATIDVDIDCTParams_computedStride, __builtin_offsetof(sATIDVDIDCTParams, computedStride) == 0x1c);
LAYOUT_CHECK(off135_sATIDVDIDCTParams_computedChromaStride, __builtin_offsetof(sATIDVDIDCTParams, computedChromaStride) == 0x20);
LAYOUT_CHECK(off136_sATIDVDIDCTParams_idctCoeffAddr24, __builtin_offsetof(sATIDVDIDCTParams, dimensionsHeightWidth) == 0x24);
LAYOUT_CHECK(off137_sATIDVDIDCTParams_strideBroadcast, __builtin_offsetof(sATIDVDIDCTParams, strideBroadcast) == 0x28);
LAYOUT_CHECK(off138_sATIDVDIDCTParams_destBaseAddress, __builtin_offsetof(sATIDVDIDCTParams, destBaseAddress) == 0x2c);
LAYOUT_CHECK(off139_sATIDVDIDCTParams_destEndAddress, __builtin_offsetof(sATIDVDIDCTParams, destEndAddress) == 0x30);
LAYOUT_CHECK(off140_sIOGLNewTextureData_typeTag, __builtin_offsetof(sIOGLNewTextureData, typeTag) == 0x00);
LAYOUT_CHECK(off141_sIOGLNewTextureReturnData_outLow, __builtin_offsetof(sIOGLNewTextureReturnData, outLow) == 0x00);
LAYOUT_CHECK(off142_sIOGLNewTextureReturnData_outHigh, __builtin_offsetof(sIOGLNewTextureReturnData, outHigh) == 0x04);
LAYOUT_CHECK(off143_sIOGLContextReadBufferData_x, __builtin_offsetof(sIOGLContextReadBufferData, x) == 0x00);
LAYOUT_CHECK(off144_sIOGLContextReadBufferData_y, __builtin_offsetof(sIOGLContextReadBufferData, y) == 0x04);
LAYOUT_CHECK(off145_sIOGLContextReadBufferData_w, __builtin_offsetof(sIOGLContextReadBufferData, w) == 0x08);
LAYOUT_CHECK(off146_sIOGLContextReadBufferData_h, __builtin_offsetof(sIOGLContextReadBufferData, h) == 0x0c);
LAYOUT_CHECK(off147_sIOGLContextReadBufferData_sourceSelector, __builtin_offsetof(sIOGLContextReadBufferData, sourceSelector) == 0x10);
LAYOUT_CHECK(off148_sIOGLContextReadBufferData_destOffset, __builtin_offsetof(sIOGLContextReadBufferData, destOffset) == 0x14);
LAYOUT_CHECK(off149_sIOGLContextReadBufferData_destPitchOrRowBytes, __builtin_offsetof(sIOGLContextReadBufferData, destPitchOrRowBytes) == 0x18);
LAYOUT_CHECK(off150_IOATIR5002DContext_sharedAllocator, __builtin_offsetof(IOATIR5002DContext, sharedAllocator) == 0x88);
LAYOUT_CHECK(off151_IOATIR5002DContext_accelerator, __builtin_offsetof(IOATIR5002DContext, accelerator) == 0x94);
LAYOUT_CHECK(off152_IOATIR5002DContext_pendingTransferBuffer, __builtin_offsetof(IOATIR5002DContext, pendingTransferBuffer) == 0x98);
LAYOUT_CHECK(off153_IOATIR5002DContext_ringSlotBufferOffset, __builtin_offsetof(IOATIR5002DContext, ringSlotBufferOffset) == 0x9c);
LAYOUT_CHECK(off154_IOATIR5002DContext_lastSubmitResult, __builtin_offsetof(IOATIR5002DContext, lastSubmitResult) == 0xa8);
LAYOUT_CHECK(off155_IOATIR5002DContext_commandBufferBase, __builtin_offsetof(IOATIR5002DContext, commandBufferBase) == 0xac);
LAYOUT_CHECK(off156_IOATIR5002DContext_boundSurface, __builtin_offsetof(IOATIR5002DContext, boundSurface) == 0x100);
LAYOUT_CHECK(off157_IOATIR5002DContext_defaultMipIndex, __builtin_offsetof(IOATIR5002DContext, defaultMipIndex) == 0x110);
LAYOUT_CHECK(off158_IOATIR5002DContext_lastBoundTexture, __builtin_offsetof(IOATIR5002DContext, lastBoundTexture) == 0x114);
LAYOUT_CHECK(off159_IOATIR500Accelerator_liveSurfaceListHead, __builtin_offsetof(IOATIR500Accelerator, liveSurfaceListHead) == 0x5c);
LAYOUT_CHECK(off160_IOATIR500Accelerator_liveGLContextListHead, __builtin_offsetof(IOATIR500Accelerator, liveGLContextListHead) == 0x60);
LAYOUT_CHECK(off161_IOATIR500Accelerator_live2DContextListHead, __builtin_offsetof(IOATIR500Accelerator, live2DContextListHead) == 0x64);
LAYOUT_CHECK(off162_IOATIR500Accelerator_liveDVDContextListHead, __builtin_offsetof(IOATIR500Accelerator, liveDVDContextListHead) == 0x68);
LAYOUT_CHECK(off163_IOATIR500DVDContext_sharedAllocator, __builtin_offsetof(IOATIR500DVDContext, sharedAllocator) == 0x84);
LAYOUT_CHECK(off164_IOATIR500DVDContext_surfaceFlagsBitmask, __builtin_offsetof(IOATIR500DVDContext, surfaceFlagsBitmask) == 0x88);
LAYOUT_CHECK(off165_IOATIR500DVDContext_accelerator, __builtin_offsetof(IOATIR500DVDContext, accelerator) == 0x8c);
LAYOUT_CHECK(off166_IOATIR500DVDContext_pendingTransferBuffer, __builtin_offsetof(IOATIR500DVDContext, pendingTransferBuffer) == 0x90);
LAYOUT_CHECK(off167_IOATIR500DVDContext_ringSlotZeroCheck, __builtin_offsetof(IOATIR500DVDContext, ringSlotZeroCheck) == 0x94);
LAYOUT_CHECK(off168_IOATIR500DVDContext_lastSubmitResult, __builtin_offsetof(IOATIR500DVDContext, lastSubmitResult) == 0xa0);
LAYOUT_CHECK(off169_IOATIR500DVDContext_commandBufferBase, __builtin_offsetof(IOATIR500DVDContext, commandBufferBase) == 0xa4);
LAYOUT_CHECK(off170_IOATIR500DVDContext_boundSurface, __builtin_offsetof(IOATIR500DVDContext, boundSurface) == 0xf8);
LAYOUT_CHECK(off171_IOATIR500GLContext_nextLiveContext, __builtin_offsetof(IOATIR500GLContext, nextLiveContext) == 0x80);
LAYOUT_CHECK(off172_IOATIR500GLContext_clientHandle, __builtin_offsetof(IOATIR500GLContext, clientHandle) == 0x88);
LAYOUT_CHECK(off173_IOATIR500GLContext_boundSurface, __builtin_offsetof(IOATIR500GLContext, boundSurface) == 0x290);
LAYOUT_CHECK(off174_IOATIR500GLContext_mipLevel, __builtin_offsetof(IOATIR500GLContext, mipLevel) == 0x29c);
LAYOUT_CHECK(off175_IOATIR500GLContext_regularMethodTable, __builtin_offsetof(IOATIR500GLContext, regularMethodTable) == 0x2a0);
LAYOUT_CHECK(off176_IOATIR500Surface_contextListHeadA, __builtin_offsetof(IOATIR500Surface, contextListHeadA) == 0x88);
LAYOUT_CHECK(off177_IOATIR500Surface_contextListHeadB, __builtin_offsetof(IOATIR500Surface, contextListHeadB) == 0x8c);
LAYOUT_CHECK(off178_IOATIR500Surface_boundDVDContext, __builtin_offsetof(IOATIR500Surface, boundDVDContext) == 0x90);
LAYOUT_CHECK(off179_IOATIR500Surface_surfaceBuffersByFormat, __builtin_offsetof(IOATIR500Surface, surfaceBuffersByFormat) == 0xb70);
LAYOUT_CHECK(off180_IOATIR500Surface_fixedSurfaceBuffer, __builtin_offsetof(IOATIR500Surface, fixedSurfaceBuffer) == 0xb94);
LAYOUT_CHECK(off181_IOATIR500Surface_accelerator, __builtin_offsetof(IOATIR500Surface, accelerator) == 0xd50);
LAYOUT_CHECK(off182_IOATIR500Surface_lastFlipFlag, __builtin_offsetof(IOATIR500Surface, lastFlipFlag) == 0xd54);
LAYOUT_CHECK(off183_IOATIR500Surface_vramInitSucceeded, __builtin_offsetof(IOATIR500Surface, vramInitSucceeded) == 0xd58);
LAYOUT_CHECK(off184_IOATIR500Surface_methodTable, __builtin_offsetof(IOATIR500Surface, methodTable) == 0xd5c);
