/* __DATA,__nl_symbol_ptr at 0xf124, 128 bytes - generated by Tools/userspace/data_sections.py */
const unsigned int sectDATA___nl_symbol_ptr[32] = {
    0x00000000, /* -> ___keymgr_global */ /* +0x0 */
    0x00000000, /* -> local */ /* +0x4 */
    0x00004740, /* -> local */ /* +0x8 */
    0x00002dc0, /* -> local */ /* +0xc */
    0x000038c0, /* -> local */ /* +0x10 */
    0x00004340, /* -> local */ /* +0x14 */
    0x0000f1b0, /* -> local */ /* +0x18 */
    0x000052f0, /* -> local */ /* +0x1c */
    0x00003930, /* -> local */ /* +0x20 */
    0x00004a00, /* -> local */ /* +0x24 */
    0x000037b0, /* -> local */ /* +0x28 */
    0x000051f0, /* -> local */ /* +0x2c */
    0x000049f0, /* -> local */ /* +0x30 */
    0x00003630, /* -> local */ /* +0x34 */
    0x00002d00, /* -> local */ /* +0x38 */
    0x00004b40, /* -> local */ /* +0x3c */
    0x00005280, /* -> local */ /* +0x40 */
    0x00002b70, /* -> local */ /* +0x44 */
    0x000056a0, /* -> local */ /* +0x48 */
    0x00003830, /* -> local */ /* +0x4c */
    0x00004a10, /* -> local */ /* +0x50 */
    0x00002e10, /* -> local */ /* +0x54 */
    0x00004280, /* -> local */ /* +0x58 */
    0x00002c70, /* -> local */ /* +0x5c */
    0x0000f1b4, /* -> local */ /* +0x60 */
    0x00002e50, /* -> local */ /* +0x64 */
    0x00003fc0, /* -> local */ /* +0x68 */
    0x00002570, /* -> local */ /* +0x6c */
    0x00004fa0, /* -> local */ /* +0x70 */
    0x00002d80, /* -> local */ /* +0x74 */
    0x00000000, /* -> __cpu_capabilities */ /* +0x78 */
    0x00000000, /* -> _mach_task_self_ */ /* +0x7c */
};
