/* __DATA,__la_symbol_ptr at 0xf0cc, 88 bytes - generated by Tools/userspace/data_sections.py */
const unsigned int sectDATA___la_symbol_ptr[22] = {
    0x00001070, /* -> _dlopen */ /* +0x0 */
    0x00001070, /* -> _malloc */ /* +0x4 */
    0x00001070, /* -> __keymgr_get_and_lock_processwide_ptr */ /* +0x8 */
    0x00001070, /* -> _free */ /* +0xc */
    0x00001070, /* -> __keymgr_set_and_unlock_processwide_ptr */ /* +0x10 */
    0x00001070, /* -> _dlsym */ /* +0x14 */
    0x00001070, /* -> _calloc */ /* +0x18 */
    0x00001070, /* -> _strcmp */ /* +0x1c */
    0x00001070, /* -> _strlcpy */ /* +0x20 */
    0x00001070, /* -> _io_connect_method_scalarI_scalarO */ /* +0x24 */
    0x00001070, /* -> _io_connect_method_scalarI_structureO */ /* +0x28 */
    0x00001070, /* -> _IOConnectMapMemory */ /* +0x2c */
    0x00001070, /* -> _memset */ /* +0x30 */
    0x00001070, /* -> _IOServiceOpen */ /* +0x34 */
    0x00001070, /* -> _CGDisplayIDToOpenGLDisplayMask */ /* +0x38 */
    0x00001070, /* -> _IOServiceClose */ /* +0x3c */
    0x00001070, /* -> _io_connect_method_scalarI_structureI */ /* +0x40 */
    0x00001070, /* -> _puts */ /* +0x44 */
    0x00001070, /* -> _memcpy */ /* +0x48 */
    0x00001070, /* -> _io_connect_method_structureI_structureO */ /* +0x4c */
    0x00001070, /* -> _cos */ /* +0x50 */
    0x00001070, /* -> _sin */ /* +0x54 */
};
