#!/usr/bin/env python3
"""gen_ava_vectors.py - issue #140 rung 2.1: build the test pictures for ava_drive.c and the EXPECTED traffic, independently, from Tools/idct_stream.py.

The harness feeds AppleVA's _DVDDriverDecodeImpl a picture descriptor + 0x1c-byte macroblock records + coefficient dwords in the DVD-driver layout
(run << 24 | level & 0xffff; FUN_97d83730 converts them in place to the AVA layout level << 16 | run << 1 | last before the ATI renderer sees them, findings section 7).
The expected IDCT streams are derived here from the AVA layout directly (idct_stream.mb_packet), so a match with the capture checks: the in-place conversion, the ATI client's
packet writer (FUN_00008510), the stream routing (intra -> stream 0, motion -> stream 1), the parameter block, and the kernel-visible buffer contents.

Writes: ava_vectors.h (C arrays for the harness), ava_expected.json (what the capture should show).  Usage: gen_ava_vectors.py [outdir]"""
import sys, os, json, struct
sys.path.insert(0, os.path.join(os.path.dirname(os.path.abspath(__file__)), '..', '..'))
import idct_stream as S

W, H = 64, 48                         # picture size = open rect; 4 x 3 macroblocks
MBW, MBH = W // 16, H // 16


def mb_record(blocks, motion=0, field_dct=0, mv=(0, 0, 0, 0, 0, 0, 0, 0)):
    counts = [len(blocks.get(b, [])) for b in range(6)]
    rec = struct.pack('>8h', *mv) + bytes([0, 0, 0, 0, motion, field_dct]) + bytes(counts)
    assert len(rec) == 0x1c
    return rec


def coef_A(blocks):
    """DVD-driver layout: byte0 = run, bytes 2-3 = level (what AppleVA's FUN_97d83730 converts); blocks in order Y0 Y1 Y2 Y3 Cb Cr"""
    out = []
    for b in range(6):
        prev = 0
        for idx, lv in blocks.get(b, []):
            out.append(((idx - prev) << 24) | (lv & 0xffff)); prev = idx + 1
    return out


PICTURES = [
    # name, pic_type, alt_scan, dst, fwd, list of (mb_index, blocks, motion, field_dct)
    ('I0 frame, zigzag', 1, 0, 0, 0, [
        (0, {0: [(0, 1024)]}, 0, 0),
        (1, {0: [(0, 1024), (3, 160)]}, 0, 0),
        (2, {0: [(0, 256)], 1: [(0, 512)], 2: [(0, 768)], 3: [(0, 1024)], 4: [(0, 384)], 5: [(0, 640)]}, 0, 0),
        (5, {0: [(0, 1024)], 2: [(0, 512)]}, 0, 1)]),
    ('I1 frame, alternate scan', 1, 1, 1, 0, [
        (0, {0: [(0, 1024), (1, 160)]}, 0, 0),
        (4, {5: [(2, 10), (9, -7), (40, 3)]}, 0, 0)]),
    ('P0 frame, forward MB + intra MB', 2, 0, 2, 0, [
        (0, {0: [(0, -64)]}, 1, 0),                 # forward-predicted MB with a residual -> stream 1
        (1, {0: [(0, 1024)]}, 0, 0)]),              # intra MB in a P picture -> stream 0,
    ('R3a one intra MB, DC only (rung 3)', 1, 0, 0, 0, [
        (0, {0: [(0, 1024)]}, 0, 0)]),
    ('R3b gain/tile probe: Y0 DC64+vertical, Y1 DC64+horizontal, Y2 DC32+vertical, Y3 DC96', 1, 0, 0, 0, [
        (0, {0: [(0, 64), (2, 40)], 1: [(0, 64), (1, 40)], 2: [(0, 32), (2, 40)], 3: [(0, 96)]}, 0, 0)]),
    ('R3c alternate scan: Y0 idx1, Y1 idx2, Y2 idx3, Y3 idx4 (each DC64 + 40)', 1, 1, 0, 0, [
        (0, {0: [(0, 64), (1, 40)], 1: [(0, 64), (2, 40)], 2: [(0, 64), (3, 40)], 3: [(0, 64), (4, 40)]}, 0, 0)]),
    ('R3d runs/clip: Y0 DC64+idx5,20,63 (runs 4,14,42), Y1 DC-400, Y2 DC2000, Y3 DC-2000', 1, 0, 0, 0, [
        (0, {0: [(0, 64), (5, 30), (20, -30), (63, 10)], 1: [(0, -400)], 2: [(0, 2000)], 3: [(0, -2000)]}, 0, 0)]),
    ('R3e field DCT: the R3b content with field_dct set', 1, 0, 0, 0, [
        (0, {0: [(0, 64), (2, 40)], 1: [(0, 64), (1, 40)], 2: [(0, 32), (2, 40)], 3: [(0, 96)]}, 0, 1)]),
    ('R3f CBP subset: only Y1 (DC128) and Y2 (DC-128) coded', 1, 0, 0, 0, [
        (0, {1: [(0, 128)], 2: [(0, -128)]}, 0, 0)])
]


def build():
    nmb = MBW * MBH
    pics, exp = [], []
    for name, ptype, alt, dst, fwd, mbs in PICTURES:
        recs = [mb_record({}) for _ in range(nmb)]
        coefs = []
        by_idx = {m[0]: m for m in mbs}
        s0, s1 = [], []
        for i in range(nmb):
            if i in by_idx:
                _, blocks, motion, fld = by_idx[i]
                recs[i] = mb_record(blocks, motion, fld)
                coefs += coef_A(blocks)
                pkt = S.mb_packet(i, MBW, blocks, fld, alt)
                (s1 if motion else s0).extend(pkt)
        pics.append(dict(name=name, ptype=ptype, alt=alt, dst=dst, fwd=fwd, recs=b''.join(recs), coefs=coefs))
        exp.append(dict(name=name, dst=dst, alt=alt, ptype=ptype, stream0=['%08x' % d for d in s0], stream1=['%08x' % d for d in s1],
                        expected_doidct=[dict(stream=0, dwords=len(s0), flag='%08x' % (0x10080 | alt << 3 | 0x20), mode='%08x' % 0)] * bool(s0) +
                                        [dict(stream=1, dwords=len(s1), flag='%08x' % (0x10080 | alt << 3), mode='%08x' % 0x8000)] * bool(s1)))
    return pics, exp


def write_header(pics, path):
    with open(path, 'w') as f:
        f.write('/* generated by gen_ava_vectors.py - do not edit */\n#define VEC_W %d\n#define VEC_H %d\n#define VEC_NMB %d\n#define VEC_NPIC %d\n' % (W, H, MBW * MBH, len(pics)))
        for i, p in enumerate(pics):
            f.write('static const unsigned char vec%d_recs[] = {%s};\n' % (i, ','.join(str(b) for b in p['recs'])))
            f.write('static const unsigned int vec%d_coefs[] = {%s};\n' % (i, ','.join('0x%08xU' % c for c in p['coefs']) or '0'))
            f.write('static const int vec%d_ncoefs = %d;\n' % (i, len(p['coefs'])))
        f.write('static const struct { const char *name; int ptype, alt, dst, fwd; const unsigned char *recs; const unsigned int *coefs; int ncoefs; } vec_pics[] = {\n')
        for i, p in enumerate(pics):
            f.write('  {"%s", %d, %d, %d, %d, vec%d_recs, vec%d_coefs, %d},\n' % (p['name'], p['ptype'], p['alt'], p['dst'], p['fwd'], i, i, len(p['coefs'])))
        f.write('};\n')


if __name__ == '__main__':
    out = sys.argv[1] if len(sys.argv) > 1 else os.path.dirname(os.path.abspath(__file__))
    pics, exp = build()
    write_header(pics, os.path.join(out, 'ava_vectors.h'))
    json.dump(dict(width=W, height=H, mbw=MBW, pictures=exp), open(os.path.join(out, 'ava_expected.json'), 'w'), indent=1)
    for e in exp:
        print('%s: stream0 %d dwords, stream1 %d dwords, doIDCT calls expected: %s' % (e['name'], len(e['stream0']), len(e['stream1']), [(d['stream'], d['dwords']) for d in e['expected_doidct']]))
