/* __DATA,__la_symbol_ptr at 0xe608, 132 bytes - generated by Tools/userspace/data_sections.py */
const unsigned int sectDATA___la_symbol_ptr[33] = {
    0x00000600, /* -> _dlopen */ /* +0x0 */
    0x00000600, /* -> _malloc */ /* +0x4 */
    0x00000600, /* -> __keymgr_get_and_lock_processwide_ptr */ /* +0x8 */
    0x00000600, /* -> _free */ /* +0xc */
    0x00000600, /* -> __keymgr_set_and_unlock_processwide_ptr */ /* +0x10 */
    0x00000600, /* -> _dlsym */ /* +0x14 */
    0x00000600, /* -> _calloc */ /* +0x18 */
    0x00000600, /* -> _strcmp */ /* +0x1c */
    0x00000600, /* -> _io_connect_method_scalarI_scalarO */ /* +0x20 */
    0x00000600, /* -> _io_connect_method_scalarI_structureO */ /* +0x24 */
    0x00000600, /* -> _CFUUIDGetConstantUUIDWithBytes */ /* +0x28 */
    0x00000600, /* -> _IOServiceOpen */ /* +0x2c */
    0x00000600, /* -> _IOObjectRelease */ /* +0x30 */
    0x00000600, /* -> _memcpy */ /* +0x34 */
    0x00000600, /* -> _CFRetain */ /* +0x38 */
    0x00000600, /* -> _IOConnectMapMemory */ /* +0x3c */
    0x00000600, /* -> _CFUUIDCreateFromUUIDBytes */ /* +0x40 */
    0x00000600, /* -> _bcopy */ /* +0x44 */
    0x00000600, /* -> _IOAccelFindAccelerator */ /* +0x48 */
    0x00000600, /* -> _CFPlugInAddInstanceForFactory */ /* +0x4c */
    0x00000600, /* -> _io_connect_method_structureI_structureO */ /* +0x50 */
    0x00000600, /* -> _IOObjectConformsTo */ /* +0x54 */
    0x00000600, /* -> _IOObjectGetClass */ /* +0x58 */
    0x00000600, /* -> _CFPlugInRemoveInstanceForFactory */ /* +0x5c */
    0x00000600, /* -> _IOServiceClose */ /* +0x60 */
    0x00000600, /* -> _io_connect_method_scalarI_structureI */ /* +0x64 */
    0x00000600, /* -> _CFEqual */ /* +0x68 */
    0x00000600, /* -> _CFRelease */ /* +0x6c */
    0x00000600, /* -> _NSIsSymbolNameDefinedWithHint */ /* +0x70 */
    0x00000600, /* -> _strcpy */ /* +0x74 */
    0x00000600, /* -> _NSLookupAndBindSymbolWithHint */ /* +0x78 */
    0x00000600, /* -> _NSAddressOfSymbol */ /* +0x7c */
    0x00000600, /* -> _strlen */ /* +0x80 */
};
