/* __DATA,__nl_symbol_ptr at 0xe68c, 16 bytes - generated by Tools/userspace/data_sections.py */
const unsigned int sectDATA___nl_symbol_ptr[4] = {
    0x00000000, /* -> ___keymgr_global */ /* +0x0 */
    0x00000000, /* -> local */ /* +0x4 */
    0x00000000, /* -> _mach_task_self_ */ /* +0x8 */
    0x00000000, /* -> _kCFBooleanTrue */ /* +0xc */
};
