/* __TEXT,__literal4 at 0xcff8, 24 bytes - generated by Tools/userspace/data_sections.py */
const unsigned int sectTEXT___literal4[6] = {
    0x41f80000, /* 31.0 */ /* +0x0 */
    0x437f0000, /* 255.0 */ /* +0x4 */
    0x3f800000, /* 1.0 */ /* +0x8 */
    0x45800000, /* 4096.0 */ /* +0xc */
    0x00000000, /* 0.0 */ /* +0x10 */
    0x41000000, /* 8.0 */ /* +0x14 */
};
