/* __TEXT,__literal8 at 0xcfd8, 32 bytes - generated by Tools/userspace/data_sections.py */
const unsigned int sectTEXT___literal8[8] = {
    0x43300000, /* 176.0 */ /* +0x0 */
    0x00000000, /* 0.0 */ /* +0x4 */
    0x43300000, /* 176.0 */ /* +0x8 */
    0x80000000, /* -0.0 */ /* +0xc */
    0x3ff00000, /* 1.875 */ /* +0x10 */
    0x00000000, /* 0.0 */ /* +0x14 */
    0x41e00000, /* 28.0 */ /* +0x18 */
    0x00000000, /* 0.0 */ /* +0x1c */
};
