#include "ghidra_c.h"

extern int dyld_stub_binding_helper();
extern int __dyld_func_lookup();
extern int _cxa_atexit_check_2();
extern int _cxa_atexit_check_1();
extern int _check_cxa_atexit();
extern int _find_atexit_10_3();
extern int FUN_000009b4();
extern int FUN_000009d4();
extern int _get_globals();
extern int FUN_00000c04();
extern int FUN_00000c24();
extern int FUN_00000c44();
extern int FUN_00000c64();
extern int FUN_00000c84();
extern int FUN_00000ca4();
extern int FUN_00000cc4();
extern int _add_routine();
extern int FUN_00000df0();
extern int FUN_00000e10();
extern int _run_routines();
extern int FUN_00000f54();
extern int FUN_00000f74();
extern int FUN_00000f94();
extern int _cxa_atexit_wrapper();
extern int FUN_000010ec();
extern int FUN_0000110c();
extern int FUN_0000112c();
extern int _our_atexit();
extern int FUN_00001208();
extern int FUN_00001228();
extern int FUN_00001248();
extern int _atexit_common();
extern int FUN_00001508();
extern int FUN_00001528();
extern int FUN_00001548();
extern int FUN_00001568();
extern int ___cxa_atexit();
extern int FUN_000015e8();
extern int _atexit();
extern int FUN_00001664();
extern int __SetSurface();
extern int __SetDestination();
extern int __LockSurface();
extern int __UnlockSurface();
extern int __SwapSurface();
extern int __Probe();
extern int _window_mode_to_ati_format();
extern int __QueryInterface();
extern int __AddRef();
extern int __DecodePixelFormat();
extern int _fillTextureWithPattern();
extern int __GetCapabilities();
extern int __GetBlitter();
extern int __Synchronize();
extern int __GetBeamPosition();
extern int __WaitSurface();
extern int _ATIRadeonX1000GAFactory();
extern int __Release();
extern int __Reset();
extern int __Start();
extern int __AllocateSurface();
extern int _radeon3DCopySetup();
extern int _radeon3DFillSetup();
extern int __Flush();
extern int __WaitComplete();
extern int __FreeSurface();
extern int _createTextureBuffer();
extern int _createOffscreenBuffer();
extern int __Stop();
extern int _radeonCopy();
extern int FUN_000055a4(int param_1,undefined4 param_2,undefined4 param_3,uint param_4,int param_5,dword param_6,double fparam_1,double fparam_2,double fparam_3,double fparam_4,double fparam_5,double fparam_6,double fparam_7,double fparam_8);
extern int _radeonFill();
extern int _radeonHighlight();
extern int _radeonSolidScanlines();
extern int _printf_LDBLStub();
extern int FUN_0000c954();
extern int FUN_0000c960();
extern int FUN_0000c968();
extern int FUN_0000c974();
extern int ___stub_getrealaddr();
extern int _CFEqual();
extern int _CFPlugInAddInstanceForFactory();
extern int _CFPlugInRemoveInstanceForFactory();
extern int _CFRelease();
extern int _CFRetain();
extern int _CFUUIDCreateFromUUIDBytes();
extern int _CFUUIDGetConstantUUIDWithBytes();
extern int _IOAccelFindAccelerator();
extern int _IOConnectMapMemory();
extern int _IOObjectConformsTo();
extern int _IOObjectGetClass();
extern int _IOObjectRelease();
extern int _IOServiceClose();
extern int _IOServiceOpen();
extern int _NSAddressOfSymbol();
extern int _NSIsSymbolNameDefinedWithHint();
extern int _NSLookupAndBindSymbolWithHint();
extern int __keymgr_get_and_lock_processwide_ptr();
extern int __keymgr_set_and_unlock_processwide_ptr();
extern int _bcopy();
extern int _calloc();
extern int _dlopen();
extern int _dlsym();
extern int _free();
extern int _io_connect_method_scalarI_scalarO();
extern int _io_connect_method_scalarI_structureI();
extern int _io_connect_method_scalarI_structureO();
extern int _io_connect_method_structureI_structureO();
extern int _malloc();
extern int _memcpy();
extern int _strcmp();
extern int _strcpy();
extern int _strlen();
extern int class();
extern unsigned char DAT_0000e018;
extern unsigned char DAT_0000e6c0;
extern unsigned char DAT_0000e6cc;
extern unsigned char DAT_0000e6d0;
extern unsigned char DAT_0000e6d4;
extern unsigned char *DAT_0000e6e4;
extern unsigned char DAT_0000e724;
extern unsigned char DAT_0000e730;
extern unsigned char DAT_0000e734;
extern unsigned char DAT_0000e738;
extern unsigned char *DAT_0000e748;
extern unsigned char PTR_0000e68c;
extern unsigned char PTR_0000e690;
extern unsigned char PTR_0000e694;
extern unsigned char PTR_0000e698;
extern int (*PTR_dyld_stub_binding_helper_0000e608)();
extern int (*PTR_dyld_stub_binding_helper_0000e60c)();
extern int (*PTR_dyld_stub_binding_helper_0000e610)();
extern int (*PTR_dyld_stub_binding_helper_0000e614)();
extern int (*PTR_dyld_stub_binding_helper_0000e618)();
extern int (*PTR_dyld_stub_binding_helper_0000e61c)();
extern int (*PTR_dyld_stub_binding_helper_0000e620)();
extern unsigned char *s__LDBL128_0000cfbc;
extern MACH_HEADER_t __mh_bundle_header;
extern float FLOAT_0000cff8;
extern float FLOAT_0000cffc;
extern float FLOAT_0000d000;
extern float FLOAT_0000d004;
extern float FLOAT_0000d008;
extern float FLOAT_0000d00c;
extern double DOUBLE_0000cfd8;
extern double DOUBLE_0000cfe0;
extern double DOUBLE_0000cfe8;
extern double DOUBLE_0000cff0;
#include "extra_decls.h"
