#include "ghidra_c.h"

extern int __dyld_func_lookup();
extern int _cxa_atexit_check_1();
extern int _check_cxa_atexit();
extern int _find_atexit_10_3();
extern int FUN_000009b4();
extern int _get_globals();
extern int FUN_00000c04();
extern int _add_routine();
extern int FUN_00000df0();
extern int _run_routines();
extern int FUN_00000f54();
extern int FUN_000010ec();
extern int FUN_00001208();
extern int _atexit_common();
extern int FUN_00001508();
extern int FUN_000015e8();
extern int _atexit();
extern int FUN_00001664();
extern undefined8 __SetSurface();
extern int __SetDestination();
extern undefined8 __LockSurface();
extern undefined8 __UnlockSurface();
extern undefined8 __SwapSurface();
extern undefined8 __Probe();
extern undefined8 _window_mode_to_ati_format();
extern undefined8 __QueryInterface();
extern undefined8 __DecodePixelFormat();
extern int _fillTextureWithPattern();
extern undefined8 __GetCapabilities();
extern int _ATIRadeonX1000GAFactory();
extern undefined8 __Reset();
extern longlong __AllocateSurface();
extern longlong _radeon3DCopySetup();
extern longlong _radeon3DFillSetup();
extern undefined8 __Flush();
extern int __WaitComplete();
extern undefined8 __FreeSurface();
extern undefined8 _createTextureBuffer();
extern undefined8 _createOffscreenBuffer();
extern undefined8 __Stop();
extern int _printf_LDBLStub();
extern int FUN_0000c954();
extern int FUN_0000c960();
extern int FUN_0000c968();
extern int FUN_0000c974();
extern int ___stub_getrealaddr();
extern int _CFEqual();
extern int _CFPlugInAddInstanceForFactory();
extern int _CFRetain();
extern int _CFUUIDCreateFromUUIDBytes();
extern int _CFUUIDGetConstantUUIDWithBytes();
extern int _IOConnectMapMemory();
extern int _IOObjectRelease();
extern int _IOServiceClose();
extern int _NSAddressOfSymbol();
extern int _NSIsSymbolNameDefinedWithHint();
extern int _NSLookupAndBindSymbolWithHint();
extern int __keymgr_get_and_lock_processwide_ptr();
extern int __keymgr_set_and_unlock_processwide_ptr();
extern int _bcopy();
extern int _calloc();
extern int _dlopen();
extern int _dlsym();
extern int _free();
extern int _io_connect_method_scalarI_scalarO();
extern int _io_connect_method_scalarI_structureI();
extern int _io_connect_method_scalarI_structureO();
extern int _malloc();
extern int _memcpy();
extern int _strcmp();
extern int _strcpy();
extern int _strlen();
extern unsigned char DAT_0000e018;
extern unsigned char DAT_0000e6c0;
extern unsigned char DAT_0000e6cc;
extern unsigned char DAT_0000e6d0;
extern unsigned char DAT_0000e6d4;
extern unsigned char *DAT_0000e6e4;
extern unsigned char DAT_0000e724;
extern unsigned char DAT_0000e730;
extern unsigned char DAT_0000e734;
extern unsigned char DAT_0000e738;
extern unsigned char *DAT_0000e748;
extern unsigned char PTR_0000e68c;
extern unsigned char PTR_0000e690;
extern unsigned char PTR_0000e694;
extern unsigned char PTR_0000e698;
extern unsigned char *s__LDBL128_0000cfbc;
extern float FLOAT_0000cff8;
extern float FLOAT_0000cffc;
extern double DOUBLE_0000cfd8;
#include "extra_decls.h"
