#!/usr/bin/env python3
"""gen_layout_checks.py  - regenerate Sources/LayoutChecks.cpp (#85).

Every class/struct member in Headers/*.h whose declaration carries a `/* +0xNN` offset comment gets a compile-time check
`__builtin_offsetof(Class, member) == 0xNN`, and every class instantiated by the shipped kext gets `sizeof(Class) == <the real object
size read from the `li r3,N` before OSObject::operator new in the stock disassembly>`. A failing check is a negative-size array typedef,
i.e. a COMPILE ERROR in Tools/build_kext.sh (gcc 4.0.1 has no static_assert; the project shims static_assert away).
Why it exists: the headers modelled object state as pads counted from offset 0, but C++ places a derived class's members after the base
class's data, so every named member of the GL/2D/DVD/Surface/Accelerator classes compiled 0x50-0x31c bytes away from its documented
offset and every object was the wrong size (the DVD context 0x6c bytes too SMALL, i.e. heap overruns) - invisible to every other check.
Run from the repo root:  python3 Tools/gen_layout_checks.py > Sources/LayoutChecks.cpp"""
import re, glob, os
HDRS = ['ATIRadeonX1000.h', 'IOATIR500Accelerator.h', 'IOATIR500GLContext.h', 'IOATIR5002DContext.h', 'IOATIR500DVDContext.h',
        'IOATIR500Surface.h', 'IOATIR500Shared.h', 'ATIR500Surface.h', 'ATIR500GLContext.h', 'ATIR5002DContext.h',
        'ATIR500DVDContext.h', 'ATIR500Memory.h']
OBJECT_SIZES = {   # from the stock kext: `li r3,N` before OSObject::operator new in each class's MetaClass::alloc
    'ATIRadeonX1000': 0xc60, 'ATIR500GLContext': 0x690, 'ATIR5002DContext': 0x12c, 'ATIR500DVDContext': 0x1e0,
    'ATIR500Surface': 0xdbc, 'ATIR500Memory': 0x14, 'IOATIR500Shared': 0x28}
BASE_SIZES = {'IOUserClient': 0x78, 'IOAccelerator': 0x50}      # the Tiger SDK's own sizes (the documented offsets assume them)
out = ['/* GENERATED by Tools/gen_layout_checks.py - do not edit. Compile-time layout checks (see that script). */',
       '#define protected public', '#define private public']
out += ['#include "../Headers/%s"' % h for h in HDRS if os.path.exists('Headers/' + h)]
out += ['#include "../Headers/ATIRadeonX1000Types.h"', '#undef protected', '#undef private', '',
        '#define LAYOUT_CHECK(name, expr) typedef char layout_check_##name[(expr) ? 1 : -1]', '']
n = 0
for c, v in BASE_SIZES.items():
    out.append('LAYOUT_CHECK(size_%s, sizeof(%s) == 0x%x);' % (c, c, v))
for c, v in sorted(OBJECT_SIZES.items()):
    out.append('LAYOUT_CHECK(size_%s, sizeof(%s) == 0x%x);' % (c, c, v))
seen = set()
for h in sorted(glob.glob('Headers/*.h')):
    cls = None
    for line in open(h):
        m = re.match(r'^\s*(?:class|struct)\s+(\w+)\s*(?::[^{;]*)?\{?\s*$', line)
        if m and not line.rstrip().endswith(';'): cls = m.group(1)
        m = re.match(r'^\s*(?!return|virtual|static|typedef|friend|inline)[A-Za-z_][\w:<>\s\*&,]*?[\s\*&](\w+)(\[[^\]]*\])?\s*;\s*/\*\s*\+0x([0-9a-fA-F]+)', line)
        if m and cls and '(' not in line.split('/*')[0] and not m.group(1).startswith('_pad') and (cls, m.group(1)) not in seen:
            seen.add((cls, m.group(1))); n += 1
            out.append('LAYOUT_CHECK(off%d_%s_%s, __builtin_offsetof(%s, %s) == 0x%s);' % (n, cls, m.group(1), cls, m.group(1), m.group(3)))
print('\n'.join(out))
