/*
 * kmod_info.c - the module-info record every Tiger kext needs, normally
 * generated by Xcode. `_start`/`_stop` are the standard C++ kext entry points
 * supplied by libkmodc++ (static constructor/destructor runners).
 * KEXT_ID / KEXT_VERSION must match the bundle's CFBundleIdentifier /
 * CFBundleVersion (defaults = the shipped driver's own).
 */
#include <mach/mach_types.h>

#ifndef KEXT_ID
#define KEXT_ID com.apple.ATIRadeonX1000
#endif
#ifndef KEXT_VERSION
#define KEXT_VERSION "4.1.9"
#endif

extern kern_return_t _start(kmod_info_t *ki, void *data);
extern kern_return_t _stop(kmod_info_t *ki, void *data);

#define KEXT_DECL(id, ver) KMOD_EXPLICIT_DECL(id, ver, _start, _stop)
__attribute__((visibility("default"))) KEXT_DECL(KEXT_ID, KEXT_VERSION)
__private_extern__ kmod_start_func_t *_realmain = 0;
__private_extern__ kmod_stop_func_t *_antimain = 0;
__private_extern__ int _kext_apple_cc = __APPLE_CC__;
