/* __DATA,__data at 0xa2f27000, 16 bytes - generated by Tools/userspace/data_sections.py */
const unsigned int sectDATA___data[4] = {
    0x92f27000, /* -> __mh_dylib_header */ /* +0x0 */
    0x00000000, /* +0x4 */
    0x00000000, /* +0x8 */
    0x00000000, /* +0xc */
};
