/* __DATA,__nl_symbol_ptr at 0xa2f27018, 12 bytes - generated by Tools/userspace/data_sections.py */
const unsigned int sectDATA___nl_symbol_ptr[3] = {
    0x92f27000, /* -> local */ /* +0x0 */
    0xa2f2700c, /* -> _gll_pkey */ /* +0x4 */
    0xa2f27004, /* -> _gll_cc */ /* +0x8 */
};
