/* __DATA,__la_symbol_ptr at 0xa2f27024, 8 bytes - generated by Tools/userspace/data_sections.py */
const unsigned int sectDATA___la_symbol_ptr[2] = {
    0x90008940, /* -> _pthread_getspecific */ /* +0x0 */
    0x9000a29c, /* -> _pthread_setspecific */ /* +0x4 */
};
